
package com.lendersoffice.los.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-02-12T14:32:34.749+05:30
 * Generated source version: 2.6.16
 * 
 */
public final class AuthServiceSoap_AuthServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.lendersoffice.com/los/webservices/", "AuthService");

    private AuthServiceSoap_AuthServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AuthService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AuthService ss = new AuthService(wsdlURL, SERVICE_NAME);
        AuthServiceSoap port = ss.getAuthServiceSoap();  
        
        {
        System.out.println("Invoking getUserAuthTicket...");
        java.lang.String _getUserAuthTicket_userName = "_getUserAuthTicket_userName-1151469747";
        java.lang.String _getUserAuthTicket_passWord = "_getUserAuthTicket_passWord293332150";
        java.lang.String _getUserAuthTicket__return = port.getUserAuthTicket(_getUserAuthTicket_userName, _getUserAuthTicket_passWord);
        System.out.println("getUserAuthTicket.result=" + _getUserAuthTicket__return);


        }
        {
        System.out.println("Invoking getPmlUserAuthTicket...");
        java.lang.String _getPmlUserAuthTicket_userName = "_getPmlUserAuthTicket_userName701180930";
        java.lang.String _getPmlUserAuthTicket_passWord = "_getPmlUserAuthTicket_passWord174548640";
        java.lang.String _getPmlUserAuthTicket_customerCode = "_getPmlUserAuthTicket_customerCode-1071670769";
        java.lang.String _getPmlUserAuthTicket__return = port.getPmlUserAuthTicket(_getPmlUserAuthTicket_userName, _getPmlUserAuthTicket_passWord, _getPmlUserAuthTicket_customerCode);
        System.out.println("getPmlUserAuthTicket.result=" + _getPmlUserAuthTicket__return);


        }
        {
        System.out.println("Invoking getActiveDirectoryUserAuthTicket...");
        java.lang.String _getActiveDirectoryUserAuthTicket_userName = "_getActiveDirectoryUserAuthTicket_userName-2060033066";
        java.lang.String _getActiveDirectoryUserAuthTicket_passWord = "_getActiveDirectoryUserAuthTicket_passWord967109024";
        java.lang.String _getActiveDirectoryUserAuthTicket_customerCode = "_getActiveDirectoryUserAuthTicket_customerCode998028541";
        java.lang.String _getActiveDirectoryUserAuthTicket__return = port.getActiveDirectoryUserAuthTicket(_getActiveDirectoryUserAuthTicket_userName, _getActiveDirectoryUserAuthTicket_passWord, _getActiveDirectoryUserAuthTicket_customerCode);
        System.out.println("getActiveDirectoryUserAuthTicket.result=" + _getActiveDirectoryUserAuthTicket__return);


        }
        {
        System.out.println("Invoking getBrokerPartnerAuthTicket...");
        java.lang.String _getBrokerPartnerAuthTicket_sSecretKey = "_getBrokerPartnerAuthTicket_sSecretKey2105725276";
        java.lang.String _getBrokerPartnerAuthTicket_brokerId = "_getBrokerPartnerAuthTicket_brokerId1020116831";
        java.lang.String _getBrokerPartnerAuthTicket_userName = "_getBrokerPartnerAuthTicket_userName-1948313020";
        java.lang.String _getBrokerPartnerAuthTicket__return = port.getBrokerPartnerAuthTicket(_getBrokerPartnerAuthTicket_sSecretKey, _getBrokerPartnerAuthTicket_brokerId, _getBrokerPartnerAuthTicket_userName);
        System.out.println("getBrokerPartnerAuthTicket.result=" + _getBrokerPartnerAuthTicket__return);


        }

        System.exit(0);
    }

}
