package com.lendersoffice.los.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-02-12T20:37:58.832+05:30
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://www.lendersoffice.com/los/webservices/", name = "LoanSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LoanSoap {

    /**
     * Update the loan file with new information. [sDataContent] The information to update. Only fields that needs updating should be sent over. [format] Identifies the output format to use. 0 - LO XML Query. <RETURN> - XML result string indicating if the Save operation succeeded or not.
     */
    @WebResult(name = "SaveResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "Save", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.Save")
    @WebMethod(operationName = "Save", action = "http://www.lendersoffice.com/los/webservices/Save")
    @ResponseWrapper(localName = "SaveResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SaveResponse")
    public java.lang.String save(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "sDataContent", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sDataContent,
        @WebParam(name = "format", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        int format
    );

    /**
     * Load the loan identified by the sLNm in Mismo 2.3.1 Format. [sTicket] Ticket returned by AuthService.asmx. [sLNm] The LendingQB Loan Name. [sXmlQuery] The Xml defines the list of fields to be included in the response. Refer to lo_xmlquery_blank.xml for an example.
     */
    @WebResult(name = "LoadMismo23ByLoanNameResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "LoadMismo23ByLoanName", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LoadMismo23ByLoanName")
    @WebMethod(operationName = "LoadMismo23ByLoanName", action = "http://www.lendersoffice.com/los/webservices/LoadMismo23ByLoanName")
    @ResponseWrapper(localName = "LoadMismo23ByLoanNameResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LoadMismo23ByLoanNameResponse")
    public java.lang.String loadMismo23ByLoanName(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "sXmlQuery", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sXmlQuery
    );

    @WebResult(name = "DeleteLoanResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "DeleteLoan", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.DeleteLoan")
    @WebMethod(operationName = "DeleteLoan", action = "http://www.lendersoffice.com/los/webservices/DeleteLoan")
    @ResponseWrapper(localName = "DeleteLoanResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.DeleteLoanResponse")
    public java.lang.String deleteLoan(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm
    );

    @WebResult(name = "BreakBrokerRateLockResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "BreakBrokerRateLock", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.BreakBrokerRateLock")
    @WebMethod(operationName = "BreakBrokerRateLock", action = "http://www.lendersoffice.com/los/webservices/BreakBrokerRateLock")
    @ResponseWrapper(localName = "BreakBrokerRateLockResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.BreakBrokerRateLockResponse")
    public java.lang.String breakBrokerRateLock(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "reason", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String reason
    );

    @WebResult(name = "SubmitTotalScorecardResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "SubmitTotalScorecard", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitTotalScorecard")
    @WebMethod(operationName = "SubmitTotalScorecard", action = "http://www.lendersoffice.com/los/webservices/SubmitTotalScorecard")
    @ResponseWrapper(localName = "SubmitTotalScorecardResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitTotalScorecardResponse")
    public java.lang.String submitTotalScorecard(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm
    );

    @WebResult(name = "LockLoanProgramWithRateOptionIdResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "LockLoanProgramWithRateOptionId", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LockLoanProgramWithRateOptionId")
    @WebMethod(operationName = "LockLoanProgramWithRateOptionId", action = "http://www.lendersoffice.com/los/webservices/LockLoanProgramWithRateOptionId")
    @ResponseWrapper(localName = "LockLoanProgramWithRateOptionIdResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LockLoanProgramWithRateOptionIdResponse")
    public java.lang.String lockLoanProgramWithRateOptionId(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "lLpTemplateId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lLpTemplateId,
        @WebParam(name = "requestedRate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedRate,
        @WebParam(name = "requestedFee", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedFee,
        @WebParam(name = "rateOptionId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String rateOptionId
    );

    @WebResult(name = "RunInternalPricingResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RunInternalPricing", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RunInternalPricing")
    @WebMethod(operationName = "RunInternalPricing", action = "http://www.lendersoffice.com/los/webservices/RunInternalPricing")
    @ResponseWrapper(localName = "RunInternalPricingResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RunInternalPricingResponse")
    public java.lang.String runInternalPricing(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "sXmlData", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sXmlData
    );

    @WebResult(name = "LockLoanProgramAndSkipDuplicateCheckResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "LockLoanProgramAndSkipDuplicateCheck", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LockLoanProgramAndSkipDuplicateCheck")
    @WebMethod(operationName = "LockLoanProgramAndSkipDuplicateCheck", action = "http://www.lendersoffice.com/los/webservices/LockLoanProgramAndSkipDuplicateCheck")
    @ResponseWrapper(localName = "LockLoanProgramAndSkipDuplicateCheckResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LockLoanProgramAndSkipDuplicateCheckResponse")
    public java.lang.String lockLoanProgramAndSkipDuplicateCheck(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "lLpTemplateId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lLpTemplateId,
        @WebParam(name = "requestedRate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedRate,
        @WebParam(name = "requestedFee", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedFee,
        @WebParam(name = "skipDuplicateCheck", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean skipDuplicateCheck
    );

    @WebResult(name = "ParseFnma32ToLoXmlResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "ParseFnma32ToLoXml", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ParseFnma32ToLoXml")
    @WebMethod(operationName = "ParseFnma32ToLoXml", action = "http://www.lendersoffice.com/los/webservices/ParseFnma32ToLoXml")
    @ResponseWrapper(localName = "ParseFnma32ToLoXmlResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ParseFnma32ToLoXmlResponse")
    public java.lang.String parseFnma32ToLoXml(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "fnma32Content", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String fnma32Content,
        @WebParam(name = "sXmlQuery", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sXmlQuery
    );

    @WebResult(name = "SubmitToDesktopUnderwriterSeamlessResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "SubmitToDesktopUnderwriterSeamless", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToDesktopUnderwriterSeamless")
    @WebMethod(operationName = "SubmitToDesktopUnderwriterSeamless", action = "http://www.lendersoffice.com/los/webservices/SubmitToDesktopUnderwriterSeamless")
    @ResponseWrapper(localName = "SubmitToDesktopUnderwriterSeamlessResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToDesktopUnderwriterSeamlessResponse")
    public java.lang.String submitToDesktopUnderwriterSeamless(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "duUserName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duUserName,
        @WebParam(name = "duPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duPassword,
        @WebParam(name = "institutionId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String institutionId,
        @WebParam(name = "craProvider", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String craProvider,
        @WebParam(name = "craLoginName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String craLoginName,
        @WebParam(name = "craPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String craPassword,
        @WebParam(name = "isCopyLiabilities", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean isCopyLiabilities
    );

    @WebResult(name = "SubmitToDesktopUnderwriterWithInstituteIdResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "SubmitToDesktopUnderwriterWithInstituteId", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToDesktopUnderwriterWithInstituteId")
    @WebMethod(operationName = "SubmitToDesktopUnderwriterWithInstituteId", action = "http://www.lendersoffice.com/los/webservices/SubmitToDesktopUnderwriterWithInstituteId")
    @ResponseWrapper(localName = "SubmitToDesktopUnderwriterWithInstituteIdResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToDesktopUnderwriterWithInstituteIdResponse")
    public java.lang.String submitToDesktopUnderwriterWithInstituteId(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "duUserName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duUserName,
        @WebParam(name = "duPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duPassword,
        @WebParam(name = "institutionId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String institutionId
    );

    /**
     * Add a PDF to a loan file. [sTicket] Ticket returned by AuthService.asmx.  [sLNm] The LendingQB Loan Name.  [documentType] The PDF document type name.  [notes] Notes related to the PDF document.  [sDataContent] The base 64 encoded PDF document.
     */
    @WebResult(name = "UploadPDFDocumentResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "UploadPDFDocument", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.UploadPDFDocument")
    @WebMethod(operationName = "UploadPDFDocument", action = "http://www.lendersoffice.com/los/webservices/UploadPDFDocument")
    @ResponseWrapper(localName = "UploadPDFDocumentResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.UploadPDFDocumentResponse")
    public java.lang.String uploadPDFDocument(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "documentType", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String documentType,
        @WebParam(name = "notes", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String notes,
        @WebParam(name = "sDataContent", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sDataContent
    );

    /**
     * Remove a particular loan name [loanName] from the list of recently modified loans.
     */
    @RequestWrapper(localName = "ClearModifiedLoanByNameByAppCode", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ClearModifiedLoanByNameByAppCode")
    @WebMethod(operationName = "ClearModifiedLoanByNameByAppCode", action = "http://www.lendersoffice.com/los/webservices/ClearModifiedLoanByNameByAppCode")
    @ResponseWrapper(localName = "ClearModifiedLoanByNameByAppCodeResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ClearModifiedLoanByNameByAppCodeResponse")
    public void clearModifiedLoanByNameByAppCode(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "loanName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String loanName,
        @WebParam(name = "appCode", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String appCode
    );

    @WebResult(name = "SubmitToFannieMaeEarlyCheckResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "SubmitToFannieMaeEarlyCheck", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToFannieMaeEarlyCheck")
    @WebMethod(operationName = "SubmitToFannieMaeEarlyCheck", action = "http://www.lendersoffice.com/los/webservices/SubmitToFannieMaeEarlyCheck")
    @ResponseWrapper(localName = "SubmitToFannieMaeEarlyCheckResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToFannieMaeEarlyCheckResponse")
    public java.lang.String submitToFannieMaeEarlyCheck(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "duUserName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duUserName,
        @WebParam(name = "duPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duPassword,
        @WebParam(name = "institutionId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String institutionId
    );

    /**
     * Retrieve a PDF document for a particular loan file. [Result] - The PDF content in base64 format.
     */
    @WebResult(name = "GetPdfByLoanNameResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetPdfByLoanName", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetPdfByLoanName")
    @WebMethod(operationName = "GetPdfByLoanName", action = "http://www.lendersoffice.com/los/webservices/GetPdfByLoanName")
    @ResponseWrapper(localName = "GetPdfByLoanNameResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetPdfByLoanNameResponse")
    public java.lang.String getPdfByLoanName(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "sPdfName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sPdfName
    );

    @WebResult(name = "RegisterLoanProgramWithRateOptionIdAndSkipDuplicateCheckResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RegisterLoanProgramWithRateOptionIdAndSkipDuplicateCheck", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RegisterLoanProgramWithRateOptionIdAndSkipDuplicateCheck")
    @WebMethod(operationName = "RegisterLoanProgramWithRateOptionIdAndSkipDuplicateCheck", action = "http://www.lendersoffice.com/los/webservices/RegisterLoanProgramWithRateOptionIdAndSkipDuplicateCheck")
    @ResponseWrapper(localName = "RegisterLoanProgramWithRateOptionIdAndSkipDuplicateCheckResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RegisterLoanProgramWithRateOptionIdAndSkipDuplicateCheckResponse")
    public java.lang.String registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "lLpTemplateId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lLpTemplateId,
        @WebParam(name = "requestedRate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedRate,
        @WebParam(name = "requestedFee", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedFee,
        @WebParam(name = "rateOptionId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String rateOptionId,
        @WebParam(name = "skipDuplicateCheck", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean skipDuplicateCheck
    );

    @WebResult(name = "RegisterLoanProgramWithRateOptionIdResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RegisterLoanProgramWithRateOptionId", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RegisterLoanProgramWithRateOptionId")
    @WebMethod(operationName = "RegisterLoanProgramWithRateOptionId", action = "http://www.lendersoffice.com/los/webservices/RegisterLoanProgramWithRateOptionId")
    @ResponseWrapper(localName = "RegisterLoanProgramWithRateOptionIdResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RegisterLoanProgramWithRateOptionIdResponse")
    public java.lang.String registerLoanProgramWithRateOptionId(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "lLpTemplateId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lLpTemplateId,
        @WebParam(name = "requestedRate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedRate,
        @WebParam(name = "requestedFee", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedFee,
        @WebParam(name = "rateOptionId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String rateOptionId
    );

    @WebResult(name = "LockLoanProgramResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "LockLoanProgram", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LockLoanProgram")
    @WebMethod(operationName = "LockLoanProgram", action = "http://www.lendersoffice.com/los/webservices/LockLoanProgram")
    @ResponseWrapper(localName = "LockLoanProgramResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LockLoanProgramResponse")
    public java.lang.String lockLoanProgram(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "lLpTemplateId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lLpTemplateId,
        @WebParam(name = "requestedRate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedRate,
        @WebParam(name = "requestedFee", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedFee
    );

    @WebResult(name = "ImportFromFannieMaeResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "ImportFromFannieMae", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ImportFromFannieMae")
    @WebMethod(operationName = "ImportFromFannieMae", action = "http://www.lendersoffice.com/los/webservices/ImportFromFannieMae")
    @ResponseWrapper(localName = "ImportFromFannieMaeResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ImportFromFannieMaeResponse")
    public java.lang.String importFromFannieMae(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "doUserName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String doUserName,
        @WebParam(name = "doPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String doPassword,
        @WebParam(name = "isImportCredit", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean isImportCredit
    );

    @WebResult(name = "RetrieveRecentActiveLoanListResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RetrieveRecentActiveLoanList", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveRecentActiveLoanList")
    @WebMethod(operationName = "RetrieveRecentActiveLoanList", action = "http://www.lendersoffice.com/los/webservices/RetrieveRecentActiveLoanList")
    @ResponseWrapper(localName = "RetrieveRecentActiveLoanListResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveRecentActiveLoanListResponse")
    public java.lang.String retrieveRecentActiveLoanList(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket
    );

    /**
     * This method returns an XML containing the list of loan files accessible to a PML user.
     */
    @WebResult(name = "RetrievePmlLoanListResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RetrievePmlLoanList", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrievePmlLoanList")
    @WebMethod(operationName = "RetrievePmlLoanList", action = "http://www.lendersoffice.com/los/webservices/RetrievePmlLoanList")
    @ResponseWrapper(localName = "RetrievePmlLoanListResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrievePmlLoanListResponse")
    public java.lang.String retrievePmlLoanList(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket
    );

    /**
     * Clear the list of recently modified loans with a Modified Date older than the [lastModifiedDate]
     */
    @RequestWrapper(localName = "ClearModifiedLoansListByAppCode", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ClearModifiedLoansListByAppCode")
    @WebMethod(operationName = "ClearModifiedLoansListByAppCode", action = "http://www.lendersoffice.com/los/webservices/ClearModifiedLoansListByAppCode")
    @ResponseWrapper(localName = "ClearModifiedLoansListByAppCodeResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ClearModifiedLoansListByAppCodeResponse")
    public void clearModifiedLoansListByAppCode(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "lastModifiedDate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        javax.xml.datatype.XMLGregorianCalendar lastModifiedDate,
        @WebParam(name = "appCode", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String appCode
    );

    @WebResult(name = "RemoveRequestedRateResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RemoveRequestedRate", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RemoveRequestedRate")
    @WebMethod(operationName = "RemoveRequestedRate", action = "http://www.lendersoffice.com/los/webservices/RemoveRequestedRate")
    @ResponseWrapper(localName = "RemoveRequestedRateResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RemoveRequestedRateResponse")
    public java.lang.String removeRequestedRate(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm
    );

    /**
     * PDF upload for integrations
     */
    @WebResult(name = "RecievePdfResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RecievePdf", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RecievePdf")
    @WebMethod(operationName = "RecievePdf", action = "http://www.lendersoffice.com/los/webservices/RecievePdf")
    @ResponseWrapper(localName = "RecievePdfResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RecievePdfResponse")
    public java.lang.String recievePdf(
        @WebParam(name = "AuthTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String authTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "DocumentClassification", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String documentClassification,
        @WebParam(name = "base64PdfContent", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String base64PdfContent
    );

    /**
     * This method returns casefile status from DU/DO. isDo determines whether the user credentials are for Desktop Originator.
     */
    @WebResult(name = "GetDesktopUnderwriterCasefileStatusResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetDesktopUnderwriterCasefileStatus", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetDesktopUnderwriterCasefileStatus")
    @WebMethod(operationName = "GetDesktopUnderwriterCasefileStatus", action = "http://www.lendersoffice.com/los/webservices/GetDesktopUnderwriterCasefileStatus")
    @ResponseWrapper(localName = "GetDesktopUnderwriterCasefileStatusResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetDesktopUnderwriterCasefileStatusResponse")
    public java.lang.String getDesktopUnderwriterCasefileStatus(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sDuCaseId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sDuCaseId,
        @WebParam(name = "duUserName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duUserName,
        @WebParam(name = "duPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duPassword,
        @WebParam(name = "isDo", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean isDo
    );

    @WebResult(name = "CreateWithULDDResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "CreateWithULDD", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateWithULDD")
    @WebMethod(operationName = "CreateWithULDD", action = "http://www.lendersoffice.com/los/webservices/CreateWithULDD")
    @ResponseWrapper(localName = "CreateWithULDDResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateWithULDDResponse")
    public java.lang.String createWithULDD(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "xml", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String xml
    );

    @WebResult(name = "PrepareLoanForResubmissionResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "PrepareLoanForResubmission", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.PrepareLoanForResubmission")
    @WebMethod(operationName = "PrepareLoanForResubmission", action = "http://www.lendersoffice.com/los/webservices/PrepareLoanForResubmission")
    @ResponseWrapper(localName = "PrepareLoanForResubmissionResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.PrepareLoanForResubmissionResponse")
    public java.lang.String prepareLoanForResubmission(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm
    );

    @WebResult(name = "ListEdocsByLoanNumberResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "ListEdocsByLoanNumber", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListEdocsByLoanNumber")
    @WebMethod(operationName = "ListEdocsByLoanNumber", action = "http://www.lendersoffice.com/los/webservices/ListEdocsByLoanNumber")
    @ResponseWrapper(localName = "ListEdocsByLoanNumberResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListEdocsByLoanNumberResponse")
    public java.lang.String listEdocsByLoanNumber(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm
    );

    @WebResult(name = "RetrieveClosingCostTemplateFeeListResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RetrieveClosingCostTemplateFeeList", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveClosingCostTemplateFeeList")
    @WebMethod(operationName = "RetrieveClosingCostTemplateFeeList", action = "http://www.lendersoffice.com/los/webservices/RetrieveClosingCostTemplateFeeList")
    @ResponseWrapper(localName = "RetrieveClosingCostTemplateFeeListResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveClosingCostTemplateFeeListResponse")
    public java.lang.String retrieveClosingCostTemplateFeeList(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "closingCostName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String closingCostName
    );

    @WebResult(name = "CreateWithFannieMaeFileResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "CreateWithFannieMaeFile", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateWithFannieMaeFile")
    @WebMethod(operationName = "CreateWithFannieMaeFile", action = "http://www.lendersoffice.com/los/webservices/CreateWithFannieMaeFile")
    @ResponseWrapper(localName = "CreateWithFannieMaeFileResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateWithFannieMaeFileResponse")
    public java.lang.String createWithFannieMaeFile(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "content", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String content
    );

    /**
     * Returns a TRUE if the loan # exists.
     */
    @WebResult(name = "IsLoanExistedResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "IsLoanExisted", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.IsLoanExisted")
    @WebMethod(operationName = "IsLoanExisted", action = "http://www.lendersoffice.com/los/webservices/IsLoanExisted")
    @ResponseWrapper(localName = "IsLoanExistedResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.IsLoanExistedResponse")
    public boolean isLoanExisted(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm
    );

    /**
     * This method returns casefile status from DU/DO. isDo determines whether the user credentials are for Desktop Originator. This method obtains CasefileID from the specified loan file.
     */
    @WebResult(name = "GetDesktopUnderwriterCasefileStatusByLoanFileResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetDesktopUnderwriterCasefileStatusByLoanFile", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetDesktopUnderwriterCasefileStatusByLoanFile")
    @WebMethod(operationName = "GetDesktopUnderwriterCasefileStatusByLoanFile", action = "http://www.lendersoffice.com/los/webservices/GetDesktopUnderwriterCasefileStatusByLoanFile")
    @ResponseWrapper(localName = "GetDesktopUnderwriterCasefileStatusByLoanFileResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetDesktopUnderwriterCasefileStatusByLoanFileResponse")
    public java.lang.String getDesktopUnderwriterCasefileStatusByLoanFile(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "duUserName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duUserName,
        @WebParam(name = "duPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duPassword,
        @WebParam(name = "isDo", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean isDo
    );

    /**
     * Do not use this method
     */
    @WebResult(name = "SaveMismo23Result", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "SaveMismo23", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SaveMismo23")
    @WebMethod(operationName = "SaveMismo23", action = "http://www.lendersoffice.com/los/webservices/SaveMismo23")
    @ResponseWrapper(localName = "SaveMismo23Response", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SaveMismo23Response")
    public java.lang.String saveMismo23(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "loanId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String loanId,
        @WebParam(name = "sXmlData", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sXmlData
    );

    /**
     * Delete an applicant from an application. [sTicket] Ticket returned by AuthServices.asmx.  [sLNm] The LendingQB Loan Name. [applicantSSN] The SSN of the borrower/coborrower we'll delete.
     */
    @WebResult(name = "DeleteApplicantResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "DeleteApplicant", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.DeleteApplicant")
    @WebMethod(operationName = "DeleteApplicant", action = "http://www.lendersoffice.com/los/webservices/DeleteApplicant")
    @ResponseWrapper(localName = "DeleteApplicantResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.DeleteApplicantResponse")
    public java.lang.String deleteApplicant(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "applicantSSN", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String applicantSSN
    );

    @WebResult(name = "ImportFromFannieMaeWithInstitutionIdResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "ImportFromFannieMaeWithInstitutionId", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ImportFromFannieMaeWithInstitutionId")
    @WebMethod(operationName = "ImportFromFannieMaeWithInstitutionId", action = "http://www.lendersoffice.com/los/webservices/ImportFromFannieMaeWithInstitutionId")
    @ResponseWrapper(localName = "ImportFromFannieMaeWithInstitutionIdResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ImportFromFannieMaeWithInstitutionIdResponse")
    public java.lang.String importFromFannieMaeWithInstitutionId(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "doUserName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String doUserName,
        @WebParam(name = "doPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String doPassword,
        @WebParam(name = "lenderInstitutionIdentifer", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lenderInstitutionIdentifer,
        @WebParam(name = "isImportCredit", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean isImportCredit
    );

    /**
     * Returns an XML string containing a list of recently modified eDocs. This method is used if the client wants to poll the LO/PML system on a fixed interval (try to keep this interval big) for recently modified files so that they can be imported into a 3rd-party LOS. Contact support for valid appCode. THIS METHOD ONLY RETURN EDOCS MODIFIED SINCE THE LAST MODIFIED DATE.
     */
    @WebResult(name = "ListModifiedEDocsByAppCodeResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "ListModifiedEDocsByAppCode", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListModifiedEDocsByAppCode")
    @WebMethod(operationName = "ListModifiedEDocsByAppCode", action = "http://www.lendersoffice.com/los/webservices/ListModifiedEDocsByAppCode")
    @ResponseWrapper(localName = "ListModifiedEDocsByAppCodeResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListModifiedEDocsByAppCodeResponse")
    public java.lang.String listModifiedEDocsByAppCode(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "appCode", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String appCode,
        @WebParam(name = "modifiedDate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String modifiedDate
    );

    /**
     * Create a new loan file and return a randomly generated loan name. [sTemplateNm] - The loan template number used to initialized the loan file. This value can be left blank.
     */
    @WebResult(name = "CreateResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "Create", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.Create")
    @WebMethod(operationName = "Create", action = "http://www.lendersoffice.com/los/webservices/Create")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateResponse")
    public java.lang.String create(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sTemplateNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTemplateNm
    );

    @WebResult(name = "CreateWithCalyxPointFileResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "CreateWithCalyxPointFile", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateWithCalyxPointFile")
    @WebMethod(operationName = "CreateWithCalyxPointFile", action = "http://www.lendersoffice.com/los/webservices/CreateWithCalyxPointFile")
    @ResponseWrapper(localName = "CreateWithCalyxPointFileResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateWithCalyxPointFileResponse")
    public java.lang.String createWithCalyxPointFile(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "base64content", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String base64Content
    );

    @WebResult(name = "RegisterLoanProgramAndSkipDuplicateCheckResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RegisterLoanProgramAndSkipDuplicateCheck", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RegisterLoanProgramAndSkipDuplicateCheck")
    @WebMethod(operationName = "RegisterLoanProgramAndSkipDuplicateCheck", action = "http://www.lendersoffice.com/los/webservices/RegisterLoanProgramAndSkipDuplicateCheck")
    @ResponseWrapper(localName = "RegisterLoanProgramAndSkipDuplicateCheckResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RegisterLoanProgramAndSkipDuplicateCheckResponse")
    public java.lang.String registerLoanProgramAndSkipDuplicateCheck(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "lLpTemplateId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lLpTemplateId,
        @WebParam(name = "requestedRate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedRate,
        @WebParam(name = "requestedFee", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedFee,
        @WebParam(name = "skipDuplicateCheck", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean skipDuplicateCheck
    );

    @WebResult(name = "RunQuickPricerResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RunQuickPricer", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RunQuickPricer")
    @WebMethod(operationName = "RunQuickPricer", action = "http://www.lendersoffice.com/los/webservices/RunQuickPricer")
    @ResponseWrapper(localName = "RunQuickPricerResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RunQuickPricerResponse")
    public java.lang.String runQuickPricer(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sXmlData", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sXmlData
    );

    /**
     * This method returns a PDF containing EDocs on the given loan file [sLNm] that are included in the shipping template [sShippingTemplateName]. EDocs with Protected status are included by default. Obsolete/Rejected docs are omitted.
     */
    @WebResult(name = "DownloadEdocsByShippingTemplateResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "DownloadEdocsByShippingTemplate", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.DownloadEdocsByShippingTemplate")
    @WebMethod(operationName = "DownloadEdocsByShippingTemplate", action = "http://www.lendersoffice.com/los/webservices/DownloadEdocsByShippingTemplate")
    @ResponseWrapper(localName = "DownloadEdocsByShippingTemplateResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.DownloadEdocsByShippingTemplateResponse")
    public byte[] downloadEdocsByShippingTemplate(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sShippingTemplateName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sShippingTemplateName,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "includeScreenedDocs", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean includeScreenedDocs,
        @WebParam(name = "includeDocsWithoutStatus", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean includeDocsWithoutStatus
    );

    @WebResult(name = "TaskResolveResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "TaskResolve", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.TaskResolve")
    @WebMethod(operationName = "TaskResolve", action = "http://www.lendersoffice.com/los/webservices/TaskResolve")
    @ResponseWrapper(localName = "TaskResolveResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.TaskResolveResponse")
    public java.lang.String taskResolve(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "taskId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String taskId,
        @WebParam(name = "subject", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String subject,
        @WebParam(name = "comment", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String comment,
        @WebParam(name = "dueDate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String dueDate,
        @WebParam(name = "assignedTo", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String assignedTo
    );

    @WebResult(name = "TaskEditResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "TaskEdit", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.TaskEdit")
    @WebMethod(operationName = "TaskEdit", action = "http://www.lendersoffice.com/los/webservices/TaskEdit")
    @ResponseWrapper(localName = "TaskEditResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.TaskEditResponse")
    public java.lang.String taskEdit(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "taskId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String taskId,
        @WebParam(name = "subject", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String subject,
        @WebParam(name = "comment", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String comment,
        @WebParam(name = "dueDate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String dueDate,
        @WebParam(name = "assignedTo", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String assignedTo
    );

    /**
     * Create new lead and return a lead name.[sTemplateNm] - The loan template number used to initialized the lead file. This value can be left blank.
     */
    @WebResult(name = "CreateLeadResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "CreateLead", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateLead")
    @WebMethod(operationName = "CreateLead", action = "http://www.lendersoffice.com/los/webservices/CreateLead")
    @ResponseWrapper(localName = "CreateLeadResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateLeadResponse")
    public java.lang.String createLead(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sTemplateNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTemplateNm
    );

    @WebResult(name = "DownloadEdocsPdfByIdResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "DownloadEdocsPdfById", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.DownloadEdocsPdfById")
    @WebMethod(operationName = "DownloadEdocsPdfById", action = "http://www.lendersoffice.com/los/webservices/DownloadEdocsPdfById")
    @ResponseWrapper(localName = "DownloadEdocsPdfByIdResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.DownloadEdocsPdfByIdResponse")
    public byte[] downloadEdocsPdfById(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "docId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String docId
    );

    /**
     * Query data from a loan file. [sTicket] Ticket returned by AuthService.asmx. [sLNm] The LendingQB Loan Name. [sXmlQuery] The Xml defines the list of fields to be included in the response. Refer to lo_xmlquery_blank.xml for an example. [format] Identifies the output format to use. 0 - LO XML Query. 3 - Calyx Point (This is returned as an encoded base-64 Xml encased string. This is because the Calyx Point file is a binary file.) 4 - Fannie Mae 3.2. 9 - MISMO 2.6
     */
    @WebResult(name = "LoadResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "Load", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.Load")
    @WebMethod(operationName = "Load", action = "http://www.lendersoffice.com/los/webservices/Load")
    @ResponseWrapper(localName = "LoadResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LoadResponse")
    public java.lang.String load(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "sXmlQuery", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sXmlQuery,
        @WebParam(name = "format", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        int format
    );

    /**
     * [OBSOLETE] Use ListModifiedLoansByAppCode.
     */
    @WebResult(name = "ListModifiedLoansResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "ListModifiedLoans", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListModifiedLoans")
    @WebMethod(operationName = "ListModifiedLoans", action = "http://www.lendersoffice.com/los/webservices/ListModifiedLoans")
    @ResponseWrapper(localName = "ListModifiedLoansResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListModifiedLoansResponse")
    public java.lang.String listModifiedLoans(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket
    );

    @WebResult(name = "CreateWithDesktopUnderwriterResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "CreateWithDesktopUnderwriter", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateWithDesktopUnderwriter")
    @WebMethod(operationName = "CreateWithDesktopUnderwriter", action = "http://www.lendersoffice.com/los/webservices/CreateWithDesktopUnderwriter")
    @ResponseWrapper(localName = "CreateWithDesktopUnderwriterResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CreateWithDesktopUnderwriterResponse")
    public java.lang.String createWithDesktopUnderwriter(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "doUserName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String doUserName,
        @WebParam(name = "doPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String doPassword,
        @WebParam(name = "sDuCaseId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sDuCaseId,
        @WebParam(name = "isImportCredit", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean isImportCredit
    );

    @WebResult(name = "ListClosingCostTemplateNameResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "ListClosingCostTemplateName", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListClosingCostTemplateName")
    @WebMethod(operationName = "ListClosingCostTemplateName", action = "http://www.lendersoffice.com/los/webservices/ListClosingCostTemplateName")
    @ResponseWrapper(localName = "ListClosingCostTemplateNameResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListClosingCostTemplateNameResponse")
    public java.lang.String listClosingCostTemplateName(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket
    );

    @WebResult(name = "RunQuickPricerForLockDeskResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RunQuickPricerForLockDesk", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RunQuickPricerForLockDesk")
    @WebMethod(operationName = "RunQuickPricerForLockDesk", action = "http://www.lendersoffice.com/los/webservices/RunQuickPricerForLockDesk")
    @ResponseWrapper(localName = "RunQuickPricerForLockDeskResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RunQuickPricerForLockDeskResponse")
    public java.lang.String runQuickPricerForLockDesk(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sXmlData", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sXmlData
    );

    @WebResult(name = "RegisterLoanProgramResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RegisterLoanProgram", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RegisterLoanProgram")
    @WebMethod(operationName = "RegisterLoanProgram", action = "http://www.lendersoffice.com/los/webservices/RegisterLoanProgram")
    @ResponseWrapper(localName = "RegisterLoanProgramResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RegisterLoanProgramResponse")
    public java.lang.String registerLoanProgram(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "lLpTemplateId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lLpTemplateId,
        @WebParam(name = "requestedRate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedRate,
        @WebParam(name = "requestedFee", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedFee
    );

    /**
     * Add a PDF to a loan file. [sTicket] Ticket returned by AuthService.asmx.  [sLNm] The LendingQB Loan Name.  [aAppId] The Application Id to contain the file.  [documentType] The PDF document type name.  [notes] Notes related to the PDF document.  [sDataContent] The base 64 encoded PDF document.
     */
    @WebResult(name = "UploadPDFDocumentToAppResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "UploadPDFDocumentToApp", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.UploadPDFDocumentToApp")
    @WebMethod(operationName = "UploadPDFDocumentToApp", action = "http://www.lendersoffice.com/los/webservices/UploadPDFDocumentToApp")
    @ResponseWrapper(localName = "UploadPDFDocumentToAppResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.UploadPDFDocumentToAppResponse")
    public java.lang.String uploadPDFDocumentToApp(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "aAppId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String aAppId,
        @WebParam(name = "documentType", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String documentType,
        @WebParam(name = "notes", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String notes,
        @WebParam(name = "sDataContent", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sDataContent
    );

    @WebResult(name = "RetrieveTaskByIdResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RetrieveTaskById", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveTaskById")
    @WebMethod(operationName = "RetrieveTaskById", action = "http://www.lendersoffice.com/los/webservices/RetrieveTaskById")
    @ResponseWrapper(localName = "RetrieveTaskByIdResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveTaskByIdResponse")
    public java.lang.String retrieveTaskById(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "taskId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String taskId
    );

    @WebResult(name = "CheckValidAppStatusResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "CheckValidAppStatus", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CheckValidAppStatus")
    @WebMethod(operationName = "CheckValidAppStatus", action = "http://www.lendersoffice.com/los/webservices/CheckValidAppStatus")
    @ResponseWrapper(localName = "CheckValidAppStatusResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.CheckValidAppStatusResponse")
    public java.lang.String checkValidAppStatus(
        @WebParam(name = "appName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String appName,
        @WebParam(name = "appVersion", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String appVersion
    );

    @WebResult(name = "SubmitToLoanProspectorSeamlessResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "SubmitToLoanProspectorSeamless", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToLoanProspectorSeamless")
    @WebMethod(operationName = "SubmitToLoanProspectorSeamless", action = "http://www.lendersoffice.com/los/webservices/SubmitToLoanProspectorSeamless")
    @ResponseWrapper(localName = "SubmitToLoanProspectorSeamlessResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToLoanProspectorSeamlessResponse")
    public java.lang.String submitToLoanProspectorSeamless(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "lpUserId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lpUserId,
        @WebParam(name = "lpPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lpPassword,
        @WebParam(name = "creditMethod", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String creditMethod,
        @WebParam(name = "craProvider", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String craProvider,
        @WebParam(name = "borrowerCreditInfoXml", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String borrowerCreditInfoXml
    );

    @WebResult(name = "ListMyActiveTaskListResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "ListMyActiveTaskList", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListMyActiveTaskList")
    @WebMethod(operationName = "ListMyActiveTaskList", action = "http://www.lendersoffice.com/los/webservices/ListMyActiveTaskList")
    @ResponseWrapper(localName = "ListMyActiveTaskListResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListMyActiveTaskListResponse")
    public java.lang.String listMyActiveTaskList(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket
    );

    @WebResult(name = "RetrieveLoanActivityListResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RetrieveLoanActivityList", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveLoanActivityList")
    @WebMethod(operationName = "RetrieveLoanActivityList", action = "http://www.lendersoffice.com/los/webservices/RetrieveLoanActivityList")
    @ResponseWrapper(localName = "RetrieveLoanActivityListResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveLoanActivityListResponse")
    public java.lang.String retrieveLoanActivityList(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "version", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        int version
    );

    @WebResult(name = "UploadLONXmlResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "UploadLONXml", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.UploadLONXml")
    @WebMethod(operationName = "UploadLONXml", action = "http://www.lendersoffice.com/los/webservices/UploadLONXml")
    @ResponseWrapper(localName = "UploadLONXmlResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.UploadLONXmlResponse")
    public java.lang.String uploadLONXml(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "loanId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String loanId,
        @WebParam(name = "sXmlData", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sXmlData
    );

    /**
     * [OBSOLETE]. Use ClearModifiedLoansListByAppCode
     */
    @RequestWrapper(localName = "ClearModifiedLoansList", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ClearModifiedLoansList")
    @WebMethod(operationName = "ClearModifiedLoansList", action = "http://www.lendersoffice.com/los/webservices/ClearModifiedLoansList")
    @ResponseWrapper(localName = "ClearModifiedLoansListResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ClearModifiedLoansListResponse")
    public void clearModifiedLoansList(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "lastModifiedDate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        javax.xml.datatype.XMLGregorianCalendar lastModifiedDate
    );

    @WebResult(name = "LockLoanProgramWithRateOptionIdAndSkipDuplicateCheckResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "LockLoanProgramWithRateOptionIdAndSkipDuplicateCheck", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LockLoanProgramWithRateOptionIdAndSkipDuplicateCheck")
    @WebMethod(operationName = "LockLoanProgramWithRateOptionIdAndSkipDuplicateCheck", action = "http://www.lendersoffice.com/los/webservices/LockLoanProgramWithRateOptionIdAndSkipDuplicateCheck")
    @ResponseWrapper(localName = "LockLoanProgramWithRateOptionIdAndSkipDuplicateCheckResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.LockLoanProgramWithRateOptionIdAndSkipDuplicateCheckResponse")
    public java.lang.String lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "lLpTemplateId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String lLpTemplateId,
        @WebParam(name = "requestedRate", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedRate,
        @WebParam(name = "requestedFee", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.math.BigDecimal requestedFee,
        @WebParam(name = "rateOptionId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String rateOptionId,
        @WebParam(name = "skipDuplicateCheck", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean skipDuplicateCheck
    );

    /**
     * This method is deprecated. Please use the RetrieveCustomReport method in Reporting.asmx instead.
     */
    @WebResult(name = "RetrieveCustomReportResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RetrieveCustomReport", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveCustomReport")
    @WebMethod(operationName = "RetrieveCustomReport", action = "http://www.lendersoffice.com/los/webservices/RetrieveCustomReport")
    @ResponseWrapper(localName = "RetrieveCustomReportResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveCustomReportResponse")
    public java.lang.String retrieveCustomReport(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sQueryNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sQueryNm,
        @WebParam(name = "includeAllWithAccess", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        boolean includeAllWithAccess
    );

    @WebResult(name = "SubmitToDesktopOriginatorResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "SubmitToDesktopOriginator", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToDesktopOriginator")
    @WebMethod(operationName = "SubmitToDesktopOriginator", action = "http://www.lendersoffice.com/los/webservices/SubmitToDesktopOriginator")
    @ResponseWrapper(localName = "SubmitToDesktopOriginatorResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToDesktopOriginatorResponse")
    public java.lang.String submitToDesktopOriginator(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "doUserName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String doUserName,
        @WebParam(name = "doPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String doPassword
    );

    @WebResult(name = "RetrieveUsersAssignedToLoanResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "RetrieveUsersAssignedToLoan", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveUsersAssignedToLoan")
    @WebMethod(operationName = "RetrieveUsersAssignedToLoan", action = "http://www.lendersoffice.com/los/webservices/RetrieveUsersAssignedToLoan")
    @ResponseWrapper(localName = "RetrieveUsersAssignedToLoanResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.RetrieveUsersAssignedToLoanResponse")
    public java.lang.String retrieveUsersAssignedToLoan(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm
    );

    @WebResult(name = "SearchResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "Search", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.Search")
    @WebMethod(operationName = "Search", action = "http://www.lendersoffice.com/los/webservices/Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SearchResponse")
    public java.lang.String search(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sSearchFilterXml", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sSearchFilterXml
    );

    @WebResult(name = "SubmitToDesktopUnderwriterResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "SubmitToDesktopUnderwriter", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToDesktopUnderwriter")
    @WebMethod(operationName = "SubmitToDesktopUnderwriter", action = "http://www.lendersoffice.com/los/webservices/SubmitToDesktopUnderwriter")
    @ResponseWrapper(localName = "SubmitToDesktopUnderwriterResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.SubmitToDesktopUnderwriterResponse")
    public java.lang.String submitToDesktopUnderwriter(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLNm", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLNm,
        @WebParam(name = "duUserName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duUserName,
        @WebParam(name = "duPassword", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String duPassword
    );

    /**
     * Returns an XML string containing a list of recently modified loans. This method is used if the client wants to poll the LO/PML system on a fixed interval (try to keep this interval big) for recently modified files so that they can be imported into a 3rd-party LOS. Contact support for valid appCode. THIS METHOD ONLY RETURN LOANS MODIFIED IN LAST 90 DAYS.
     */
    @WebResult(name = "ListModifiedLoansByAppCodeResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "ListModifiedLoansByAppCode", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListModifiedLoansByAppCode")
    @WebMethod(operationName = "ListModifiedLoansByAppCode", action = "http://www.lendersoffice.com/los/webservices/ListModifiedLoansByAppCode")
    @ResponseWrapper(localName = "ListModifiedLoansByAppCodeResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ListModifiedLoansByAppCodeResponse")
    public java.lang.String listModifiedLoansByAppCode(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "appCode", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String appCode
    );

    /**
     * [OBSOLETE] Use ClearModifiedLoanByNameByAppCode.
     */
    @RequestWrapper(localName = "ClearModifiedLoanByName", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ClearModifiedLoanByName")
    @WebMethod(operationName = "ClearModifiedLoanByName", action = "http://www.lendersoffice.com/los/webservices/ClearModifiedLoanByName")
    @ResponseWrapper(localName = "ClearModifiedLoanByNameResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.ClearModifiedLoanByNameResponse")
    public void clearModifiedLoanByName(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "loanName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String loanName
    );
}
