package com.lendersoffice.los.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.16 2015-03-30T16:06:00.202+05:30
 * Generated source version: 2.6.16
 * 
 */
public final class AppViewSoap_AppViewSoap_Client {

	private static final QName SERVICE_NAME = new QName(
	        "http://www.lendersoffice.com/los/webservices/", "AppView");

	private AppViewSoap_AppViewSoap_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = AppView.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		AppView ss = new AppView(wsdlURL, SERVICE_NAME);
		AppViewSoap port = ss.getAppViewSoap();

		{
			System.out.println("Invoking getViewDesktopUrl...");
			java.lang.String _getViewDesktopUrl_sTicket = "_getViewDesktopUrl_sTicket-1387422286";
			java.lang.String _getViewDesktopUrl__return = port
			        .getViewDesktopUrl(_getViewDesktopUrl_sTicket);
			System.out.println("getViewDesktopUrl.result="
			        + _getViewDesktopUrl__return);

		}
		{
			System.out.println("Invoking getViewLoanUrl...");
			java.lang.String _getViewLoanUrl_sTicket = "_getViewLoanUrl_sTicket-1694792999";
			java.lang.String _getViewLoanUrl_sLoanName = "_getViewLoanUrl_sLoanName869007539";
			java.lang.String _getViewLoanUrl__return = port.getViewLoanUrl(
			        _getViewLoanUrl_sTicket, _getViewLoanUrl_sLoanName);
			System.out.println("getViewLoanUrl.result="
			        + _getViewLoanUrl__return);

		}
		{
			System.out.println("Invoking getPmlPipelineUrl...");
			java.lang.String _getPmlPipelineUrl_sTicket = "_getPmlPipelineUrl_sTicket-1037339837";
			java.lang.String _getPmlPipelineUrl__return = port
			        .getPmlPipelineUrl(_getPmlPipelineUrl_sTicket);
			System.out.println("getPmlPipelineUrl.result="
			        + _getPmlPipelineUrl__return);

		}
		{
			System.out.println("Invoking getPmlLoanUrl...");
			java.lang.String _getPmlLoanUrl_sTicket = "_getPmlLoanUrl_sTicket255101008";
			java.lang.String _getPmlLoanUrl_sLoanName = "_getPmlLoanUrl_sLoanName-313141840";
			java.lang.String _getPmlLoanUrl__return = port.getPmlLoanUrl(
			        _getPmlLoanUrl_sTicket, _getPmlLoanUrl_sLoanName);
			System.out
			        .println("getPmlLoanUrl.result=" + _getPmlLoanUrl__return);

		}

		System.exit(0);
	}

}
