package com.lendersoffice.los.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-03-30T16:06:00.264+05:30
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://www.lendersoffice.com/los/webservices/", name = "AppViewSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AppViewSoap {

    /**
     * Returns a partial URL to redirect the client directly to the LendingQB Desktop (Pipeline View). The partial URL should be prefixed with https://secure.lendersoffice.com
     */
    @WebResult(name = "GetViewDesktopUrlResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetViewDesktopUrl", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetViewDesktopUrl")
    @WebMethod(operationName = "GetViewDesktopUrl", action = "http://www.lendersoffice.com/los/webservices/GetViewDesktopUrl")
    @ResponseWrapper(localName = "GetViewDesktopUrlResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetViewDesktopUrlResponse")
    public java.lang.String getViewDesktopUrl(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket
    );

    @WebResult(name = "GetViewLoanUrlResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetViewLoanUrl", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetViewLoanUrl")
    @WebMethod(operationName = "GetViewLoanUrl", action = "http://www.lendersoffice.com/los/webservices/GetViewLoanUrl")
    @ResponseWrapper(localName = "GetViewLoanUrlResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetViewLoanUrlResponse")
    public java.lang.String getViewLoanUrl(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLoanName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLoanName
    );

    /**
     * Returns a partial URL to redirect the client directly to the PriceMyLoan.com Pipeline View. The partial URL should be prefixed with https://secure.pricemyloan.com
     */
    @WebResult(name = "GetPmlPipelineUrlResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetPmlPipelineUrl", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetPmlPipelineUrl")
    @WebMethod(operationName = "GetPmlPipelineUrl", action = "http://www.lendersoffice.com/los/webservices/GetPmlPipelineUrl")
    @ResponseWrapper(localName = "GetPmlPipelineUrlResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetPmlPipelineUrlResponse")
    public java.lang.String getPmlPipelineUrl(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket
    );

    /**
     * Returns a partial URL to redirect the client directly into the PriceMyLoan.com Loan File View (Step #1). The partial URL should be prefixed with https://secure.pricemyloan.com.
     */
    @WebResult(name = "GetPmlLoanUrlResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetPmlLoanUrl", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetPmlLoanUrl")
    @WebMethod(operationName = "GetPmlLoanUrl", action = "http://www.lendersoffice.com/los/webservices/GetPmlLoanUrl")
    @ResponseWrapper(localName = "GetPmlLoanUrlResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetPmlLoanUrlResponse")
    public java.lang.String getPmlLoanUrl(
        @WebParam(name = "sTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sTicket,
        @WebParam(name = "sLoanName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sLoanName
    );
}
