
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.lendersoffice.los.webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-03-30T16:06:00.241+05:30
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "AppView",
                      portName = "AppViewSoap",
                      targetNamespace = "http://www.lendersoffice.com/los/webservices/",
                      wsdlLocation = "https://webservices.lendingqb.com/los/webservice/AppView.asmx?WSDL",
                      endpointInterface = "com.lendersoffice.los.webservices.AppViewSoap")
                      
public class AppViewSoapImpl1 implements AppViewSoap {

    private static final Logger LOG = Logger.getLogger(AppViewSoapImpl1.class.getName());

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.AppViewSoap#getViewDesktopUrl(java.lang.String  sTicket )*
     */
    public java.lang.String getViewDesktopUrl(java.lang.String sTicket) { 
        LOG.info("Executing operation getViewDesktopUrl");
        System.out.println(sTicket);
        try {
            java.lang.String _return = "_return1810643882";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.AppViewSoap#getViewLoanUrl(java.lang.String  sTicket ,)java.lang.String  sLoanName )*
     */
    public java.lang.String getViewLoanUrl(java.lang.String sTicket,java.lang.String sLoanName) { 
        LOG.info("Executing operation getViewLoanUrl");
        System.out.println(sTicket);
        System.out.println(sLoanName);
        try {
            java.lang.String _return = "_return-139839104";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.AppViewSoap#getPmlPipelineUrl(java.lang.String  sTicket )*
     */
    public java.lang.String getPmlPipelineUrl(java.lang.String sTicket) { 
        LOG.info("Executing operation getPmlPipelineUrl");
        System.out.println(sTicket);
        try {
            java.lang.String _return = "_return861457709";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.AppViewSoap#getPmlLoanUrl(java.lang.String  sTicket ,)java.lang.String  sLoanName )*
     */
    public java.lang.String getPmlLoanUrl(java.lang.String sTicket,java.lang.String sLoanName) { 
        LOG.info("Executing operation getPmlLoanUrl");
        System.out.println(sTicket);
        System.out.println(sLoanName);
        try {
            java.lang.String _return = "_return-730450253";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
