package com.lendersoffice.los.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-02-12T14:32:34.898+05:30
 * Generated source version: 2.6.16
 * 
 */
@WebServiceClient(name = "AuthService", 
                  wsdlLocation = "https://webservices.lendingqb.com/los/webservice/Authservice.asmx?WSDL",
                  targetNamespace = "http://www.lendersoffice.com/los/webservices/") 
public class AuthService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.lendersoffice.com/los/webservices/", "AuthService");
    public final static QName AuthServiceSoap = new QName("http://www.lendersoffice.com/los/webservices/", "AuthServiceSoap");
    public final static QName AuthServiceSoap12 = new QName("http://www.lendersoffice.com/los/webservices/", "AuthServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("https://webservices.lendingqb.com/los/webservice/Authservice.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://webservices.lendingqb.com/los/webservice/Authservice.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public AuthService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuthService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuthService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuthService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AuthServiceSoap
     */
    @WebEndpoint(name = "AuthServiceSoap")
    public AuthServiceSoap getAuthServiceSoap() {
        return super.getPort(AuthServiceSoap, AuthServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthServiceSoap
     */
    @WebEndpoint(name = "AuthServiceSoap")
    public AuthServiceSoap getAuthServiceSoap(WebServiceFeature... features) {
        return super.getPort(AuthServiceSoap, AuthServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns AuthServiceSoap
     */
    @WebEndpoint(name = "AuthServiceSoap12")
    public AuthServiceSoap getAuthServiceSoap12() {
        return super.getPort(AuthServiceSoap12, AuthServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthServiceSoap
     */
    @WebEndpoint(name = "AuthServiceSoap12")
    public AuthServiceSoap getAuthServiceSoap12(WebServiceFeature... features) {
        return super.getPort(AuthServiceSoap12, AuthServiceSoap.class, features);
    }

}
