
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.lendersoffice.los.webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-02-12T14:32:34.840+05:30
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "AuthService",
                      portName = "AuthServiceSoap",
                      targetNamespace = "http://www.lendersoffice.com/los/webservices/",
                      wsdlLocation = "https://webservices.lendingqb.com/los/webservice/Authservice.asmx?WSDL",
                      endpointInterface = "com.lendersoffice.los.webservices.AuthServiceSoap")
                      
public class AuthServiceSoapImpl implements AuthServiceSoap {

    private static final Logger LOG = Logger.getLogger(AuthServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.AuthServiceSoap#getUserAuthTicket(java.lang.String  userName ,)java.lang.String  passWord )*
     */
    public java.lang.String getUserAuthTicket(java.lang.String userName,java.lang.String passWord) { 
        LOG.info("Executing operation getUserAuthTicket");
        System.out.println(userName);
        System.out.println(passWord);
        try {
            java.lang.String _return = "_return-1645502727";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.AuthServiceSoap#getPmlUserAuthTicket(java.lang.String  userName ,)java.lang.String  passWord ,)java.lang.String  customerCode )*
     */
    public java.lang.String getPmlUserAuthTicket(java.lang.String userName,java.lang.String passWord,java.lang.String customerCode) { 
        LOG.info("Executing operation getPmlUserAuthTicket");
        System.out.println(userName);
        System.out.println(passWord);
        System.out.println(customerCode);
        try {
            java.lang.String _return = "_return-553754088";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.AuthServiceSoap#getActiveDirectoryUserAuthTicket(java.lang.String  userName ,)java.lang.String  passWord ,)java.lang.String  customerCode )*
     */
    public java.lang.String getActiveDirectoryUserAuthTicket(java.lang.String userName,java.lang.String passWord,java.lang.String customerCode) { 
        LOG.info("Executing operation getActiveDirectoryUserAuthTicket");
        System.out.println(userName);
        System.out.println(passWord);
        System.out.println(customerCode);
        try {
            java.lang.String _return = "_return-1989331780";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.AuthServiceSoap#getBrokerPartnerAuthTicket(java.lang.String  sSecretKey ,)java.lang.String  brokerId ,)java.lang.String  userName )*
     */
    public java.lang.String getBrokerPartnerAuthTicket(java.lang.String sSecretKey,java.lang.String brokerId,java.lang.String userName) { 
        LOG.info("Executing operation getBrokerPartnerAuthTicket");
        System.out.println(sSecretKey);
        System.out.println(brokerId);
        System.out.println(userName);
        try {
            java.lang.String _return = "_return-878585007";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
