package com.lendersoffice.los.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-02-12T14:32:34.883+05:30
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://www.lendersoffice.com/los/webservices/", name = "AuthServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AuthServiceSoap {

    /**
     * Convert a LendingQB user's login and password into an auth-ticket.
     */
    @WebResult(name = "GetUserAuthTicketResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetUserAuthTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetUserAuthTicket")
    @WebMethod(operationName = "GetUserAuthTicket", action = "http://www.lendersoffice.com/los/webservices/GetUserAuthTicket")
    @ResponseWrapper(localName = "GetUserAuthTicketResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetUserAuthTicketResponse")
    public java.lang.String getUserAuthTicket(
        @WebParam(name = "userName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String userName,
        @WebParam(name = "passWord", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String passWord
    );

    /**
     * Convert a PriceMyLoan.com user's login and password into an auth-ticket. [customerCode] Your PML Support Engineer can provide you with your company's customer code if you do not know what it is. The format for this customer code is PML#### (i.e., PML0445)
     */
    @WebResult(name = "GetPmlUserAuthTicketResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetPmlUserAuthTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetPmlUserAuthTicket")
    @WebMethod(operationName = "GetPmlUserAuthTicket", action = "http://www.lendersoffice.com/los/webservices/GetPmlUserAuthTicket")
    @ResponseWrapper(localName = "GetPmlUserAuthTicketResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetPmlUserAuthTicketResponse")
    public java.lang.String getPmlUserAuthTicket(
        @WebParam(name = "userName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String userName,
        @WebParam(name = "passWord", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String passWord,
        @WebParam(name = "customerCode", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String customerCode
    );

    /**
     * Authenticate a LendingQB user against an Active Directory database. Returns an auth-ticket. 
     *                         [customerCode] Contact your account administrator to request your company's customer code. 
     *                         This method should only be used to authenticate LendingQB users that have been configured for Active Directory authentication.
     */
    @WebResult(name = "GetActiveDirectoryUserAuthTicketResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetActiveDirectoryUserAuthTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetActiveDirectoryUserAuthTicket")
    @WebMethod(operationName = "GetActiveDirectoryUserAuthTicket", action = "http://www.lendersoffice.com/los/webservices/GetActiveDirectoryUserAuthTicket")
    @ResponseWrapper(localName = "GetActiveDirectoryUserAuthTicketResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetActiveDirectoryUserAuthTicketResponse")
    public java.lang.String getActiveDirectoryUserAuthTicket(
        @WebParam(name = "userName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String userName,
        @WebParam(name = "passWord", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String passWord,
        @WebParam(name = "customerCode", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String customerCode
    );

    /**
     * This method is deprecated. Please use GetUserAuthTicket instead.
     */
    @WebResult(name = "GetBrokerPartnerAuthTicketResult", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
    @RequestWrapper(localName = "GetBrokerPartnerAuthTicket", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetBrokerPartnerAuthTicket")
    @WebMethod(operationName = "GetBrokerPartnerAuthTicket", action = "http://www.lendersoffice.com/los/webservices/GetBrokerPartnerAuthTicket")
    @ResponseWrapper(localName = "GetBrokerPartnerAuthTicketResponse", targetNamespace = "http://www.lendersoffice.com/los/webservices/", className = "com.lendersoffice.los.webservices.GetBrokerPartnerAuthTicketResponse")
    public java.lang.String getBrokerPartnerAuthTicket(
        @WebParam(name = "sSecretKey", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String sSecretKey,
        @WebParam(name = "brokerId", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String brokerId,
        @WebParam(name = "userName", targetNamespace = "http://www.lendersoffice.com/los/webservices/")
        java.lang.String userName
    );
}
