
package com.lendersoffice.los.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-02-12T20:37:58.634+05:30
 * Generated source version: 2.6.16
 * 
 */
public final class LoanSoap_LoanSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.lendersoffice.com/los/webservices/", "Loan");

    private LoanSoap_LoanSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Loan.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Loan ss = new Loan(wsdlURL, SERVICE_NAME);
        LoanSoap port = ss.getLoanSoap12();  
        
        {
        System.out.println("Invoking save...");
        java.lang.String _save_sTicket = "_save_sTicket680297963";
        java.lang.String _save_sLNm = "_save_sLNm1401904064";
        java.lang.String _save_sDataContent = "_save_sDataContent608009071";
        int _save_format = -1838213937;
        java.lang.String _save__return = port.save(_save_sTicket, _save_sLNm, _save_sDataContent, _save_format);
        System.out.println("save.result=" + _save__return);


        }
        {
        System.out.println("Invoking loadMismo23ByLoanName...");
        java.lang.String _loadMismo23ByLoanName_sTicket = "_loadMismo23ByLoanName_sTicket-567448129";
        java.lang.String _loadMismo23ByLoanName_sLNm = "_loadMismo23ByLoanName_sLNm-1868054759";
        java.lang.String _loadMismo23ByLoanName_sXmlQuery = "_loadMismo23ByLoanName_sXmlQuery1453892456";
        java.lang.String _loadMismo23ByLoanName__return = port.loadMismo23ByLoanName(_loadMismo23ByLoanName_sTicket, _loadMismo23ByLoanName_sLNm, _loadMismo23ByLoanName_sXmlQuery);
        System.out.println("loadMismo23ByLoanName.result=" + _loadMismo23ByLoanName__return);


        }
        {
        System.out.println("Invoking deleteLoan...");
        java.lang.String _deleteLoan_sTicket = "_deleteLoan_sTicket1266451580";
        java.lang.String _deleteLoan_sLNm = "_deleteLoan_sLNm-1772456144";
        java.lang.String _deleteLoan__return = port.deleteLoan(_deleteLoan_sTicket, _deleteLoan_sLNm);
        System.out.println("deleteLoan.result=" + _deleteLoan__return);


        }
        {
        System.out.println("Invoking breakBrokerRateLock...");
        java.lang.String _breakBrokerRateLock_sTicket = "_breakBrokerRateLock_sTicket-1253937576";
        java.lang.String _breakBrokerRateLock_sLNm = "_breakBrokerRateLock_sLNm108615943";
        java.lang.String _breakBrokerRateLock_reason = "_breakBrokerRateLock_reason-725497731";
        java.lang.String _breakBrokerRateLock__return = port.breakBrokerRateLock(_breakBrokerRateLock_sTicket, _breakBrokerRateLock_sLNm, _breakBrokerRateLock_reason);
        System.out.println("breakBrokerRateLock.result=" + _breakBrokerRateLock__return);


        }
        {
        System.out.println("Invoking submitTotalScorecard...");
        java.lang.String _submitTotalScorecard_sTicket = "_submitTotalScorecard_sTicket-1065846853";
        java.lang.String _submitTotalScorecard_sLNm = "_submitTotalScorecard_sLNm1165031341";
        java.lang.String _submitTotalScorecard__return = port.submitTotalScorecard(_submitTotalScorecard_sTicket, _submitTotalScorecard_sLNm);
        System.out.println("submitTotalScorecard.result=" + _submitTotalScorecard__return);


        }
        {
        System.out.println("Invoking lockLoanProgramWithRateOptionId...");
        java.lang.String _lockLoanProgramWithRateOptionId_sTicket = "_lockLoanProgramWithRateOptionId_sTicket998473503";
        java.lang.String _lockLoanProgramWithRateOptionId_sLNm = "_lockLoanProgramWithRateOptionId_sLNm188975671";
        java.lang.String _lockLoanProgramWithRateOptionId_lLpTemplateId = "_lockLoanProgramWithRateOptionId_lLpTemplateId1963532943";
        java.math.BigDecimal _lockLoanProgramWithRateOptionId_requestedRate = new java.math.BigDecimal("-6383218584625942034.3708631281663854484");
        java.math.BigDecimal _lockLoanProgramWithRateOptionId_requestedFee = new java.math.BigDecimal("5106926129463035847.2006795023226535599");
        java.lang.String _lockLoanProgramWithRateOptionId_rateOptionId = "_lockLoanProgramWithRateOptionId_rateOptionId-865698259";
        java.lang.String _lockLoanProgramWithRateOptionId__return = port.lockLoanProgramWithRateOptionId(_lockLoanProgramWithRateOptionId_sTicket, _lockLoanProgramWithRateOptionId_sLNm, _lockLoanProgramWithRateOptionId_lLpTemplateId, _lockLoanProgramWithRateOptionId_requestedRate, _lockLoanProgramWithRateOptionId_requestedFee, _lockLoanProgramWithRateOptionId_rateOptionId);
        System.out.println("lockLoanProgramWithRateOptionId.result=" + _lockLoanProgramWithRateOptionId__return);


        }
        {
        System.out.println("Invoking runInternalPricing...");
        java.lang.String _runInternalPricing_sTicket = "_runInternalPricing_sTicket-1874003984";
        java.lang.String _runInternalPricing_sLNm = "_runInternalPricing_sLNm205615488";
        java.lang.String _runInternalPricing_sXmlData = "_runInternalPricing_sXmlData1185563460";
        java.lang.String _runInternalPricing__return = port.runInternalPricing(_runInternalPricing_sTicket, _runInternalPricing_sLNm, _runInternalPricing_sXmlData);
        System.out.println("runInternalPricing.result=" + _runInternalPricing__return);


        }
        {
        System.out.println("Invoking lockLoanProgramAndSkipDuplicateCheck...");
        java.lang.String _lockLoanProgramAndSkipDuplicateCheck_sTicket = "_lockLoanProgramAndSkipDuplicateCheck_sTicket1819569323";
        java.lang.String _lockLoanProgramAndSkipDuplicateCheck_sLNm = "_lockLoanProgramAndSkipDuplicateCheck_sLNm-1157215283";
        java.lang.String _lockLoanProgramAndSkipDuplicateCheck_lLpTemplateId = "_lockLoanProgramAndSkipDuplicateCheck_lLpTemplateId891760589";
        java.math.BigDecimal _lockLoanProgramAndSkipDuplicateCheck_requestedRate = new java.math.BigDecimal("4945167877185530798.7191894822223357883");
        java.math.BigDecimal _lockLoanProgramAndSkipDuplicateCheck_requestedFee = new java.math.BigDecimal("5572899727257620590.779917395717361726");
        boolean _lockLoanProgramAndSkipDuplicateCheck_skipDuplicateCheck = true;
        java.lang.String _lockLoanProgramAndSkipDuplicateCheck__return = port.lockLoanProgramAndSkipDuplicateCheck(_lockLoanProgramAndSkipDuplicateCheck_sTicket, _lockLoanProgramAndSkipDuplicateCheck_sLNm, _lockLoanProgramAndSkipDuplicateCheck_lLpTemplateId, _lockLoanProgramAndSkipDuplicateCheck_requestedRate, _lockLoanProgramAndSkipDuplicateCheck_requestedFee, _lockLoanProgramAndSkipDuplicateCheck_skipDuplicateCheck);
        System.out.println("lockLoanProgramAndSkipDuplicateCheck.result=" + _lockLoanProgramAndSkipDuplicateCheck__return);


        }
        {
        System.out.println("Invoking parseFnma32ToLoXml...");
        java.lang.String _parseFnma32ToLoXml_sTicket = "_parseFnma32ToLoXml_sTicket338985049";
        java.lang.String _parseFnma32ToLoXml_fnma32Content = "_parseFnma32ToLoXml_fnma32Content2099872232";
        java.lang.String _parseFnma32ToLoXml_sXmlQuery = "_parseFnma32ToLoXml_sXmlQuery-396333693";
        java.lang.String _parseFnma32ToLoXml__return = port.parseFnma32ToLoXml(_parseFnma32ToLoXml_sTicket, _parseFnma32ToLoXml_fnma32Content, _parseFnma32ToLoXml_sXmlQuery);
        System.out.println("parseFnma32ToLoXml.result=" + _parseFnma32ToLoXml__return);


        }
        {
        System.out.println("Invoking submitToDesktopUnderwriterSeamless...");
        java.lang.String _submitToDesktopUnderwriterSeamless_sTicket = "_submitToDesktopUnderwriterSeamless_sTicket1776325791";
        java.lang.String _submitToDesktopUnderwriterSeamless_sLNm = "_submitToDesktopUnderwriterSeamless_sLNm-2022804153";
        java.lang.String _submitToDesktopUnderwriterSeamless_duUserName = "_submitToDesktopUnderwriterSeamless_duUserName1430762080";
        java.lang.String _submitToDesktopUnderwriterSeamless_duPassword = "_submitToDesktopUnderwriterSeamless_duPassword-1340270820";
        java.lang.String _submitToDesktopUnderwriterSeamless_institutionId = "_submitToDesktopUnderwriterSeamless_institutionId1491992475";
        java.lang.String _submitToDesktopUnderwriterSeamless_craProvider = "_submitToDesktopUnderwriterSeamless_craProvider-266514190";
        java.lang.String _submitToDesktopUnderwriterSeamless_craLoginName = "_submitToDesktopUnderwriterSeamless_craLoginName-1976679829";
        java.lang.String _submitToDesktopUnderwriterSeamless_craPassword = "_submitToDesktopUnderwriterSeamless_craPassword899315133";
        boolean _submitToDesktopUnderwriterSeamless_isCopyLiabilities = false;
        java.lang.String _submitToDesktopUnderwriterSeamless__return = port.submitToDesktopUnderwriterSeamless(_submitToDesktopUnderwriterSeamless_sTicket, _submitToDesktopUnderwriterSeamless_sLNm, _submitToDesktopUnderwriterSeamless_duUserName, _submitToDesktopUnderwriterSeamless_duPassword, _submitToDesktopUnderwriterSeamless_institutionId, _submitToDesktopUnderwriterSeamless_craProvider, _submitToDesktopUnderwriterSeamless_craLoginName, _submitToDesktopUnderwriterSeamless_craPassword, _submitToDesktopUnderwriterSeamless_isCopyLiabilities);
        System.out.println("submitToDesktopUnderwriterSeamless.result=" + _submitToDesktopUnderwriterSeamless__return);


        }
        {
        System.out.println("Invoking submitToDesktopUnderwriterWithInstituteId...");
        java.lang.String _submitToDesktopUnderwriterWithInstituteId_sTicket = "_submitToDesktopUnderwriterWithInstituteId_sTicket155071397";
        java.lang.String _submitToDesktopUnderwriterWithInstituteId_sLNm = "_submitToDesktopUnderwriterWithInstituteId_sLNm344581630";
        java.lang.String _submitToDesktopUnderwriterWithInstituteId_duUserName = "_submitToDesktopUnderwriterWithInstituteId_duUserName-455000709";
        java.lang.String _submitToDesktopUnderwriterWithInstituteId_duPassword = "_submitToDesktopUnderwriterWithInstituteId_duPassword1698011160";
        java.lang.String _submitToDesktopUnderwriterWithInstituteId_institutionId = "_submitToDesktopUnderwriterWithInstituteId_institutionId642468402";
        java.lang.String _submitToDesktopUnderwriterWithInstituteId__return = port.submitToDesktopUnderwriterWithInstituteId(_submitToDesktopUnderwriterWithInstituteId_sTicket, _submitToDesktopUnderwriterWithInstituteId_sLNm, _submitToDesktopUnderwriterWithInstituteId_duUserName, _submitToDesktopUnderwriterWithInstituteId_duPassword, _submitToDesktopUnderwriterWithInstituteId_institutionId);
        System.out.println("submitToDesktopUnderwriterWithInstituteId.result=" + _submitToDesktopUnderwriterWithInstituteId__return);


        }
        {
        System.out.println("Invoking uploadPDFDocument...");
        java.lang.String _uploadPDFDocument_sTicket = "_uploadPDFDocument_sTicket1236675106";
        java.lang.String _uploadPDFDocument_sLNm = "_uploadPDFDocument_sLNm1668910691";
        java.lang.String _uploadPDFDocument_documentType = "_uploadPDFDocument_documentType2031047910";
        java.lang.String _uploadPDFDocument_notes = "_uploadPDFDocument_notes-391002328";
        java.lang.String _uploadPDFDocument_sDataContent = "_uploadPDFDocument_sDataContent-254982118";
        java.lang.String _uploadPDFDocument__return = port.uploadPDFDocument(_uploadPDFDocument_sTicket, _uploadPDFDocument_sLNm, _uploadPDFDocument_documentType, _uploadPDFDocument_notes, _uploadPDFDocument_sDataContent);
        System.out.println("uploadPDFDocument.result=" + _uploadPDFDocument__return);


        }
        {
        System.out.println("Invoking clearModifiedLoanByNameByAppCode...");
        java.lang.String _clearModifiedLoanByNameByAppCode_sTicket = "_clearModifiedLoanByNameByAppCode_sTicket-1660276014";
        java.lang.String _clearModifiedLoanByNameByAppCode_loanName = "_clearModifiedLoanByNameByAppCode_loanName586127126";
        java.lang.String _clearModifiedLoanByNameByAppCode_appCode = "_clearModifiedLoanByNameByAppCode_appCode353483589";
        port.clearModifiedLoanByNameByAppCode(_clearModifiedLoanByNameByAppCode_sTicket, _clearModifiedLoanByNameByAppCode_loanName, _clearModifiedLoanByNameByAppCode_appCode);


        }
        {
        System.out.println("Invoking submitToFannieMaeEarlyCheck...");
        java.lang.String _submitToFannieMaeEarlyCheck_sTicket = "_submitToFannieMaeEarlyCheck_sTicket-1908439349";
        java.lang.String _submitToFannieMaeEarlyCheck_sLNm = "_submitToFannieMaeEarlyCheck_sLNm1954344707";
        java.lang.String _submitToFannieMaeEarlyCheck_duUserName = "_submitToFannieMaeEarlyCheck_duUserName1524484459";
        java.lang.String _submitToFannieMaeEarlyCheck_duPassword = "_submitToFannieMaeEarlyCheck_duPassword-1916894935";
        java.lang.String _submitToFannieMaeEarlyCheck_institutionId = "_submitToFannieMaeEarlyCheck_institutionId-818622888";
        java.lang.String _submitToFannieMaeEarlyCheck__return = port.submitToFannieMaeEarlyCheck(_submitToFannieMaeEarlyCheck_sTicket, _submitToFannieMaeEarlyCheck_sLNm, _submitToFannieMaeEarlyCheck_duUserName, _submitToFannieMaeEarlyCheck_duPassword, _submitToFannieMaeEarlyCheck_institutionId);
        System.out.println("submitToFannieMaeEarlyCheck.result=" + _submitToFannieMaeEarlyCheck__return);


        }
        {
        System.out.println("Invoking getPdfByLoanName...");
        java.lang.String _getPdfByLoanName_sTicket = "_getPdfByLoanName_sTicket2053092841";
        java.lang.String _getPdfByLoanName_sLNm = "_getPdfByLoanName_sLNm106369364";
        java.lang.String _getPdfByLoanName_sPdfName = "_getPdfByLoanName_sPdfName-869420979";
        java.lang.String _getPdfByLoanName__return = port.getPdfByLoanName(_getPdfByLoanName_sTicket, _getPdfByLoanName_sLNm, _getPdfByLoanName_sPdfName);
        System.out.println("getPdfByLoanName.result=" + _getPdfByLoanName__return);


        }
        {
        System.out.println("Invoking registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck...");
        java.lang.String _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket = "_registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket2097238540";
        java.lang.String _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm = "_registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm-1134307521";
        java.lang.String _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId = "_registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId1732961649";
        java.math.BigDecimal _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedRate = new java.math.BigDecimal("5435223741487412349.695389580237731755");
        java.math.BigDecimal _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedFee = new java.math.BigDecimal("-4495405117335975443.7212230350625303437");
        java.lang.String _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId = "_registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId149715329";
        boolean _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_skipDuplicateCheck = true;
        java.lang.String _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck__return = port.registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck(_registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedRate, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedFee, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_skipDuplicateCheck);
        System.out.println("registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck.result=" + _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck__return);


        }
        {
        System.out.println("Invoking registerLoanProgramWithRateOptionId...");
        java.lang.String _registerLoanProgramWithRateOptionId_sTicket = "_registerLoanProgramWithRateOptionId_sTicket1117847963";
        java.lang.String _registerLoanProgramWithRateOptionId_sLNm = "_registerLoanProgramWithRateOptionId_sLNm-1343045919";
        java.lang.String _registerLoanProgramWithRateOptionId_lLpTemplateId = "_registerLoanProgramWithRateOptionId_lLpTemplateId1765856894";
        java.math.BigDecimal _registerLoanProgramWithRateOptionId_requestedRate = new java.math.BigDecimal("407744377547476082.7937963946697167478");
        java.math.BigDecimal _registerLoanProgramWithRateOptionId_requestedFee = new java.math.BigDecimal("-475269087840715672.4658659895089602771");
        java.lang.String _registerLoanProgramWithRateOptionId_rateOptionId = "_registerLoanProgramWithRateOptionId_rateOptionId-1364520798";
        java.lang.String _registerLoanProgramWithRateOptionId__return = port.registerLoanProgramWithRateOptionId(_registerLoanProgramWithRateOptionId_sTicket, _registerLoanProgramWithRateOptionId_sLNm, _registerLoanProgramWithRateOptionId_lLpTemplateId, _registerLoanProgramWithRateOptionId_requestedRate, _registerLoanProgramWithRateOptionId_requestedFee, _registerLoanProgramWithRateOptionId_rateOptionId);
        System.out.println("registerLoanProgramWithRateOptionId.result=" + _registerLoanProgramWithRateOptionId__return);


        }
        {
        System.out.println("Invoking lockLoanProgram...");
        java.lang.String _lockLoanProgram_sTicket = "_lockLoanProgram_sTicket1301410706";
        java.lang.String _lockLoanProgram_sLNm = "_lockLoanProgram_sLNm-1740585870";
        java.lang.String _lockLoanProgram_lLpTemplateId = "_lockLoanProgram_lLpTemplateId483985522";
        java.math.BigDecimal _lockLoanProgram_requestedRate = new java.math.BigDecimal("3460438723440379483.7839598135478419493");
        java.math.BigDecimal _lockLoanProgram_requestedFee = new java.math.BigDecimal("8152902887830307739.7419598987122240917");
        java.lang.String _lockLoanProgram__return = port.lockLoanProgram(_lockLoanProgram_sTicket, _lockLoanProgram_sLNm, _lockLoanProgram_lLpTemplateId, _lockLoanProgram_requestedRate, _lockLoanProgram_requestedFee);
        System.out.println("lockLoanProgram.result=" + _lockLoanProgram__return);


        }
        {
        System.out.println("Invoking importFromFannieMae...");
        java.lang.String _importFromFannieMae_sTicket = "_importFromFannieMae_sTicket-1469928835";
        java.lang.String _importFromFannieMae_sLNm = "_importFromFannieMae_sLNm-381457951";
        java.lang.String _importFromFannieMae_doUserName = "_importFromFannieMae_doUserName726105350";
        java.lang.String _importFromFannieMae_doPassword = "_importFromFannieMae_doPassword1872343788";
        boolean _importFromFannieMae_isImportCredit = true;
        java.lang.String _importFromFannieMae__return = port.importFromFannieMae(_importFromFannieMae_sTicket, _importFromFannieMae_sLNm, _importFromFannieMae_doUserName, _importFromFannieMae_doPassword, _importFromFannieMae_isImportCredit);
        System.out.println("importFromFannieMae.result=" + _importFromFannieMae__return);


        }
        {
        System.out.println("Invoking retrieveRecentActiveLoanList...");
        java.lang.String _retrieveRecentActiveLoanList_sTicket = "_retrieveRecentActiveLoanList_sTicket-1850352109";
        java.lang.String _retrieveRecentActiveLoanList__return = port.retrieveRecentActiveLoanList(_retrieveRecentActiveLoanList_sTicket);
        System.out.println("retrieveRecentActiveLoanList.result=" + _retrieveRecentActiveLoanList__return);


        }
        {
        System.out.println("Invoking retrievePmlLoanList...");
        java.lang.String _retrievePmlLoanList_sTicket = "_retrievePmlLoanList_sTicket471357457";
        java.lang.String _retrievePmlLoanList__return = port.retrievePmlLoanList(_retrievePmlLoanList_sTicket);
        System.out.println("retrievePmlLoanList.result=" + _retrievePmlLoanList__return);


        }
        {
        System.out.println("Invoking clearModifiedLoansListByAppCode...");
        java.lang.String _clearModifiedLoansListByAppCode_sTicket = "_clearModifiedLoansListByAppCode_sTicket-957639424";
        javax.xml.datatype.XMLGregorianCalendar _clearModifiedLoansListByAppCode_lastModifiedDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-02-12T20:37:58.677+05:30");
        java.lang.String _clearModifiedLoansListByAppCode_appCode = "_clearModifiedLoansListByAppCode_appCode1426123437";
        port.clearModifiedLoansListByAppCode(_clearModifiedLoansListByAppCode_sTicket, _clearModifiedLoansListByAppCode_lastModifiedDate, _clearModifiedLoansListByAppCode_appCode);


        }
        {
        System.out.println("Invoking removeRequestedRate...");
        java.lang.String _removeRequestedRate_sTicket = "_removeRequestedRate_sTicket-1160857799";
        java.lang.String _removeRequestedRate_sLNm = "_removeRequestedRate_sLNm-1136069550";
        java.lang.String _removeRequestedRate__return = port.removeRequestedRate(_removeRequestedRate_sTicket, _removeRequestedRate_sLNm);
        System.out.println("removeRequestedRate.result=" + _removeRequestedRate__return);


        }
        {
        System.out.println("Invoking recievePdf...");
        java.lang.String _recievePdf_authTicket = "_recievePdf_authTicket777739961";
        java.lang.String _recievePdf_sLNm = "_recievePdf_sLNm-835019744";
        java.lang.String _recievePdf_documentClassification = "_recievePdf_documentClassification-1860586603";
        java.lang.String _recievePdf_base64PdfContent = "_recievePdf_base64PdfContent-1500831259";
        java.lang.String _recievePdf__return = port.recievePdf(_recievePdf_authTicket, _recievePdf_sLNm, _recievePdf_documentClassification, _recievePdf_base64PdfContent);
        System.out.println("recievePdf.result=" + _recievePdf__return);


        }
        {
        System.out.println("Invoking getDesktopUnderwriterCasefileStatus...");
        java.lang.String _getDesktopUnderwriterCasefileStatus_sTicket = "_getDesktopUnderwriterCasefileStatus_sTicket-1350554121";
        java.lang.String _getDesktopUnderwriterCasefileStatus_sDuCaseId = "_getDesktopUnderwriterCasefileStatus_sDuCaseId-506646947";
        java.lang.String _getDesktopUnderwriterCasefileStatus_duUserName = "_getDesktopUnderwriterCasefileStatus_duUserName-1407161610";
        java.lang.String _getDesktopUnderwriterCasefileStatus_duPassword = "_getDesktopUnderwriterCasefileStatus_duPassword1624390025";
        boolean _getDesktopUnderwriterCasefileStatus_isDo = false;
        java.lang.String _getDesktopUnderwriterCasefileStatus__return = port.getDesktopUnderwriterCasefileStatus(_getDesktopUnderwriterCasefileStatus_sTicket, _getDesktopUnderwriterCasefileStatus_sDuCaseId, _getDesktopUnderwriterCasefileStatus_duUserName, _getDesktopUnderwriterCasefileStatus_duPassword, _getDesktopUnderwriterCasefileStatus_isDo);
        System.out.println("getDesktopUnderwriterCasefileStatus.result=" + _getDesktopUnderwriterCasefileStatus__return);


        }
        {
        System.out.println("Invoking createWithULDD...");
        java.lang.String _createWithULDD_sTicket = "_createWithULDD_sTicket-346490038";
        java.lang.String _createWithULDD_xml = "_createWithULDD_xml-1089842611";
        java.lang.String _createWithULDD__return = port.createWithULDD(_createWithULDD_sTicket, _createWithULDD_xml);
        System.out.println("createWithULDD.result=" + _createWithULDD__return);


        }
        {
        System.out.println("Invoking prepareLoanForResubmission...");
        java.lang.String _prepareLoanForResubmission_sTicket = "_prepareLoanForResubmission_sTicket-132408669";
        java.lang.String _prepareLoanForResubmission_sLNm = "_prepareLoanForResubmission_sLNm-1149808271";
        java.lang.String _prepareLoanForResubmission__return = port.prepareLoanForResubmission(_prepareLoanForResubmission_sTicket, _prepareLoanForResubmission_sLNm);
        System.out.println("prepareLoanForResubmission.result=" + _prepareLoanForResubmission__return);


        }
        {
        System.out.println("Invoking listEdocsByLoanNumber...");
        java.lang.String _listEdocsByLoanNumber_sTicket = "_listEdocsByLoanNumber_sTicket-638211505";
        java.lang.String _listEdocsByLoanNumber_sLNm = "_listEdocsByLoanNumber_sLNm503374976";
        java.lang.String _listEdocsByLoanNumber__return = port.listEdocsByLoanNumber(_listEdocsByLoanNumber_sTicket, _listEdocsByLoanNumber_sLNm);
        System.out.println("listEdocsByLoanNumber.result=" + _listEdocsByLoanNumber__return);


        }
        {
        System.out.println("Invoking retrieveClosingCostTemplateFeeList...");
        java.lang.String _retrieveClosingCostTemplateFeeList_sTicket = "_retrieveClosingCostTemplateFeeList_sTicket1144161672";
        java.lang.String _retrieveClosingCostTemplateFeeList_closingCostName = "_retrieveClosingCostTemplateFeeList_closingCostName560030892";
        java.lang.String _retrieveClosingCostTemplateFeeList__return = port.retrieveClosingCostTemplateFeeList(_retrieveClosingCostTemplateFeeList_sTicket, _retrieveClosingCostTemplateFeeList_closingCostName);
        System.out.println("retrieveClosingCostTemplateFeeList.result=" + _retrieveClosingCostTemplateFeeList__return);


        }
        {
        System.out.println("Invoking createWithFannieMaeFile...");
        java.lang.String _createWithFannieMaeFile_sTicket = "_createWithFannieMaeFile_sTicket1267555900";
        java.lang.String _createWithFannieMaeFile_content = "_createWithFannieMaeFile_content1433207934";
        java.lang.String _createWithFannieMaeFile__return = port.createWithFannieMaeFile(_createWithFannieMaeFile_sTicket, _createWithFannieMaeFile_content);
        System.out.println("createWithFannieMaeFile.result=" + _createWithFannieMaeFile__return);


        }
        {
        System.out.println("Invoking isLoanExisted...");
        java.lang.String _isLoanExisted_sTicket = "_isLoanExisted_sTicket895538683";
        java.lang.String _isLoanExisted_sLNm = "_isLoanExisted_sLNm-1679883113";
        boolean _isLoanExisted__return = port.isLoanExisted(_isLoanExisted_sTicket, _isLoanExisted_sLNm);
        System.out.println("isLoanExisted.result=" + _isLoanExisted__return);


        }
        {
        System.out.println("Invoking getDesktopUnderwriterCasefileStatusByLoanFile...");
        java.lang.String _getDesktopUnderwriterCasefileStatusByLoanFile_sTicket = "_getDesktopUnderwriterCasefileStatusByLoanFile_sTicket321019241";
        java.lang.String _getDesktopUnderwriterCasefileStatusByLoanFile_sLNm = "_getDesktopUnderwriterCasefileStatusByLoanFile_sLNm601877650";
        java.lang.String _getDesktopUnderwriterCasefileStatusByLoanFile_duUserName = "_getDesktopUnderwriterCasefileStatusByLoanFile_duUserName-49126924";
        java.lang.String _getDesktopUnderwriterCasefileStatusByLoanFile_duPassword = "_getDesktopUnderwriterCasefileStatusByLoanFile_duPassword142054856";
        boolean _getDesktopUnderwriterCasefileStatusByLoanFile_isDo = true;
        java.lang.String _getDesktopUnderwriterCasefileStatusByLoanFile__return = port.getDesktopUnderwriterCasefileStatusByLoanFile(_getDesktopUnderwriterCasefileStatusByLoanFile_sTicket, _getDesktopUnderwriterCasefileStatusByLoanFile_sLNm, _getDesktopUnderwriterCasefileStatusByLoanFile_duUserName, _getDesktopUnderwriterCasefileStatusByLoanFile_duPassword, _getDesktopUnderwriterCasefileStatusByLoanFile_isDo);
        System.out.println("getDesktopUnderwriterCasefileStatusByLoanFile.result=" + _getDesktopUnderwriterCasefileStatusByLoanFile__return);


        }
        {
        System.out.println("Invoking saveMismo23...");
        java.lang.String _saveMismo23_sTicket = "_saveMismo23_sTicket-1312080132";
        java.lang.String _saveMismo23_loanId = "_saveMismo23_loanId-964099933";
        java.lang.String _saveMismo23_sXmlData = "_saveMismo23_sXmlData289704777";
        java.lang.String _saveMismo23__return = port.saveMismo23(_saveMismo23_sTicket, _saveMismo23_loanId, _saveMismo23_sXmlData);
        System.out.println("saveMismo23.result=" + _saveMismo23__return);


        }
        {
        System.out.println("Invoking deleteApplicant...");
        java.lang.String _deleteApplicant_sTicket = "_deleteApplicant_sTicket879669557";
        java.lang.String _deleteApplicant_sLNm = "_deleteApplicant_sLNm944835517";
        java.lang.String _deleteApplicant_applicantSSN = "_deleteApplicant_applicantSSN-635732557";
        java.lang.String _deleteApplicant__return = port.deleteApplicant(_deleteApplicant_sTicket, _deleteApplicant_sLNm, _deleteApplicant_applicantSSN);
        System.out.println("deleteApplicant.result=" + _deleteApplicant__return);


        }
        {
        System.out.println("Invoking importFromFannieMaeWithInstitutionId...");
        java.lang.String _importFromFannieMaeWithInstitutionId_sTicket = "_importFromFannieMaeWithInstitutionId_sTicket-134344054";
        java.lang.String _importFromFannieMaeWithInstitutionId_sLNm = "_importFromFannieMaeWithInstitutionId_sLNm-480744195";
        java.lang.String _importFromFannieMaeWithInstitutionId_doUserName = "_importFromFannieMaeWithInstitutionId_doUserName-743579726";
        java.lang.String _importFromFannieMaeWithInstitutionId_doPassword = "_importFromFannieMaeWithInstitutionId_doPassword-1134953261";
        java.lang.String _importFromFannieMaeWithInstitutionId_lenderInstitutionIdentifer = "_importFromFannieMaeWithInstitutionId_lenderInstitutionIdentifer-1080948072";
        boolean _importFromFannieMaeWithInstitutionId_isImportCredit = true;
        java.lang.String _importFromFannieMaeWithInstitutionId__return = port.importFromFannieMaeWithInstitutionId(_importFromFannieMaeWithInstitutionId_sTicket, _importFromFannieMaeWithInstitutionId_sLNm, _importFromFannieMaeWithInstitutionId_doUserName, _importFromFannieMaeWithInstitutionId_doPassword, _importFromFannieMaeWithInstitutionId_lenderInstitutionIdentifer, _importFromFannieMaeWithInstitutionId_isImportCredit);
        System.out.println("importFromFannieMaeWithInstitutionId.result=" + _importFromFannieMaeWithInstitutionId__return);


        }
        {
        System.out.println("Invoking listModifiedEDocsByAppCode...");
        java.lang.String _listModifiedEDocsByAppCode_sTicket = "_listModifiedEDocsByAppCode_sTicket-1152634652";
        java.lang.String _listModifiedEDocsByAppCode_appCode = "_listModifiedEDocsByAppCode_appCode924225905";
        java.lang.String _listModifiedEDocsByAppCode_modifiedDate = "_listModifiedEDocsByAppCode_modifiedDate-1646871921";
        java.lang.String _listModifiedEDocsByAppCode__return = port.listModifiedEDocsByAppCode(_listModifiedEDocsByAppCode_sTicket, _listModifiedEDocsByAppCode_appCode, _listModifiedEDocsByAppCode_modifiedDate);
        System.out.println("listModifiedEDocsByAppCode.result=" + _listModifiedEDocsByAppCode__return);


        }
        {
        System.out.println("Invoking create...");
        java.lang.String _create_sTicket = "_create_sTicket666847818";
        java.lang.String _create_sTemplateNm = "_create_sTemplateNm-625886178";
        java.lang.String _create__return = port.create(_create_sTicket, _create_sTemplateNm);
        System.out.println("create.result=" + _create__return);


        }
        {
        System.out.println("Invoking createWithCalyxPointFile...");
        java.lang.String _createWithCalyxPointFile_sTicket = "_createWithCalyxPointFile_sTicket1425608392";
        java.lang.String _createWithCalyxPointFile_base64Content = "_createWithCalyxPointFile_base64Content571341645";
        java.lang.String _createWithCalyxPointFile__return = port.createWithCalyxPointFile(_createWithCalyxPointFile_sTicket, _createWithCalyxPointFile_base64Content);
        System.out.println("createWithCalyxPointFile.result=" + _createWithCalyxPointFile__return);


        }
        {
        System.out.println("Invoking registerLoanProgramAndSkipDuplicateCheck...");
        java.lang.String _registerLoanProgramAndSkipDuplicateCheck_sTicket = "_registerLoanProgramAndSkipDuplicateCheck_sTicket-2037798591";
        java.lang.String _registerLoanProgramAndSkipDuplicateCheck_sLNm = "_registerLoanProgramAndSkipDuplicateCheck_sLNm-261314625";
        java.lang.String _registerLoanProgramAndSkipDuplicateCheck_lLpTemplateId = "_registerLoanProgramAndSkipDuplicateCheck_lLpTemplateId-1926147043";
        java.math.BigDecimal _registerLoanProgramAndSkipDuplicateCheck_requestedRate = new java.math.BigDecimal("5117435424080039767.2607443238659529028");
        java.math.BigDecimal _registerLoanProgramAndSkipDuplicateCheck_requestedFee = new java.math.BigDecimal("-5483576330990339512.47392626933923689");
        boolean _registerLoanProgramAndSkipDuplicateCheck_skipDuplicateCheck = false;
        java.lang.String _registerLoanProgramAndSkipDuplicateCheck__return = port.registerLoanProgramAndSkipDuplicateCheck(_registerLoanProgramAndSkipDuplicateCheck_sTicket, _registerLoanProgramAndSkipDuplicateCheck_sLNm, _registerLoanProgramAndSkipDuplicateCheck_lLpTemplateId, _registerLoanProgramAndSkipDuplicateCheck_requestedRate, _registerLoanProgramAndSkipDuplicateCheck_requestedFee, _registerLoanProgramAndSkipDuplicateCheck_skipDuplicateCheck);
        System.out.println("registerLoanProgramAndSkipDuplicateCheck.result=" + _registerLoanProgramAndSkipDuplicateCheck__return);


        }
        {
        System.out.println("Invoking runQuickPricer...");
        java.lang.String _runQuickPricer_sTicket = "_runQuickPricer_sTicket-2005572130";
        java.lang.String _runQuickPricer_sXmlData = "_runQuickPricer_sXmlData160488175";
        java.lang.String _runQuickPricer__return = port.runQuickPricer(_runQuickPricer_sTicket, _runQuickPricer_sXmlData);
        System.out.println("runQuickPricer.result=" + _runQuickPricer__return);


        }
        {
        System.out.println("Invoking downloadEdocsByShippingTemplate...");
        java.lang.String _downloadEdocsByShippingTemplate_sTicket = "_downloadEdocsByShippingTemplate_sTicket-1945966068";
        java.lang.String _downloadEdocsByShippingTemplate_sShippingTemplateName = "_downloadEdocsByShippingTemplate_sShippingTemplateName-990767741";
        java.lang.String _downloadEdocsByShippingTemplate_sLNm = "_downloadEdocsByShippingTemplate_sLNm253130387";
        boolean _downloadEdocsByShippingTemplate_includeScreenedDocs = true;
        boolean _downloadEdocsByShippingTemplate_includeDocsWithoutStatus = false;
        byte[] _downloadEdocsByShippingTemplate__return = port.downloadEdocsByShippingTemplate(_downloadEdocsByShippingTemplate_sTicket, _downloadEdocsByShippingTemplate_sShippingTemplateName, _downloadEdocsByShippingTemplate_sLNm, _downloadEdocsByShippingTemplate_includeScreenedDocs, _downloadEdocsByShippingTemplate_includeDocsWithoutStatus);
        System.out.println("downloadEdocsByShippingTemplate.result=" + _downloadEdocsByShippingTemplate__return);


        }
        {
        System.out.println("Invoking taskResolve...");
        java.lang.String _taskResolve_sTicket = "_taskResolve_sTicket-396028518";
        java.lang.String _taskResolve_taskId = "_taskResolve_taskId1871063673";
        java.lang.String _taskResolve_subject = "_taskResolve_subject-1985150797";
        java.lang.String _taskResolve_comment = "_taskResolve_comment2141525609";
        java.lang.String _taskResolve_dueDate = "_taskResolve_dueDate-40814187";
        java.lang.String _taskResolve_assignedTo = "_taskResolve_assignedTo852391006";
        java.lang.String _taskResolve__return = port.taskResolve(_taskResolve_sTicket, _taskResolve_taskId, _taskResolve_subject, _taskResolve_comment, _taskResolve_dueDate, _taskResolve_assignedTo);
        System.out.println("taskResolve.result=" + _taskResolve__return);


        }
        {
        System.out.println("Invoking taskEdit...");
        java.lang.String _taskEdit_sTicket = "_taskEdit_sTicket1454658715";
        java.lang.String _taskEdit_taskId = "_taskEdit_taskId-1185247356";
        java.lang.String _taskEdit_subject = "_taskEdit_subject418439001";
        java.lang.String _taskEdit_comment = "_taskEdit_comment-813406934";
        java.lang.String _taskEdit_dueDate = "_taskEdit_dueDate1489401324";
        java.lang.String _taskEdit_assignedTo = "_taskEdit_assignedTo-920328280";
        java.lang.String _taskEdit__return = port.taskEdit(_taskEdit_sTicket, _taskEdit_taskId, _taskEdit_subject, _taskEdit_comment, _taskEdit_dueDate, _taskEdit_assignedTo);
        System.out.println("taskEdit.result=" + _taskEdit__return);


        }
        {
        System.out.println("Invoking createLead...");
        java.lang.String _createLead_sTicket = "_createLead_sTicket1205360943";
        java.lang.String _createLead_sTemplateNm = "_createLead_sTemplateNm530204556";
        java.lang.String _createLead__return = port.createLead(_createLead_sTicket, _createLead_sTemplateNm);
        System.out.println("createLead.result=" + _createLead__return);


        }
        {
        System.out.println("Invoking downloadEdocsPdfById...");
        java.lang.String _downloadEdocsPdfById_sTicket = "_downloadEdocsPdfById_sTicket-863798400";
        java.lang.String _downloadEdocsPdfById_docId = "_downloadEdocsPdfById_docId1851588109";
        byte[] _downloadEdocsPdfById__return = port.downloadEdocsPdfById(_downloadEdocsPdfById_sTicket, _downloadEdocsPdfById_docId);
        System.out.println("downloadEdocsPdfById.result=" + _downloadEdocsPdfById__return);


        }
        {
        System.out.println("Invoking load...");
        java.lang.String _load_sTicket = "_load_sTicket-476772169";
        java.lang.String _load_sLNm = "_load_sLNm667242965";
        java.lang.String _load_sXmlQuery = "_load_sXmlQuery-335270022";
        int _load_format = -757409894;
        java.lang.String _load__return = port.load(_load_sTicket, _load_sLNm, _load_sXmlQuery, _load_format);
        System.out.println("load.result=" + _load__return);


        }
        {
        System.out.println("Invoking listModifiedLoans...");
        java.lang.String _listModifiedLoans_sTicket = "_listModifiedLoans_sTicket-1351699173";
        java.lang.String _listModifiedLoans__return = port.listModifiedLoans(_listModifiedLoans_sTicket);
        System.out.println("listModifiedLoans.result=" + _listModifiedLoans__return);


        }
        {
        System.out.println("Invoking createWithDesktopUnderwriter...");
        java.lang.String _createWithDesktopUnderwriter_sTicket = "_createWithDesktopUnderwriter_sTicket-1586359773";
        java.lang.String _createWithDesktopUnderwriter_doUserName = "_createWithDesktopUnderwriter_doUserName776237722";
        java.lang.String _createWithDesktopUnderwriter_doPassword = "_createWithDesktopUnderwriter_doPassword-1980800597";
        java.lang.String _createWithDesktopUnderwriter_sDuCaseId = "_createWithDesktopUnderwriter_sDuCaseId1386975366";
        boolean _createWithDesktopUnderwriter_isImportCredit = false;
        java.lang.String _createWithDesktopUnderwriter__return = port.createWithDesktopUnderwriter(_createWithDesktopUnderwriter_sTicket, _createWithDesktopUnderwriter_doUserName, _createWithDesktopUnderwriter_doPassword, _createWithDesktopUnderwriter_sDuCaseId, _createWithDesktopUnderwriter_isImportCredit);
        System.out.println("createWithDesktopUnderwriter.result=" + _createWithDesktopUnderwriter__return);


        }
        {
        System.out.println("Invoking listClosingCostTemplateName...");
        java.lang.String _listClosingCostTemplateName_sTicket = "_listClosingCostTemplateName_sTicket377487570";
        java.lang.String _listClosingCostTemplateName__return = port.listClosingCostTemplateName(_listClosingCostTemplateName_sTicket);
        System.out.println("listClosingCostTemplateName.result=" + _listClosingCostTemplateName__return);


        }
        {
        System.out.println("Invoking runQuickPricerForLockDesk...");
        java.lang.String _runQuickPricerForLockDesk_sTicket = "_runQuickPricerForLockDesk_sTicket-1007608556";
        java.lang.String _runQuickPricerForLockDesk_sXmlData = "_runQuickPricerForLockDesk_sXmlData-859135785";
        java.lang.String _runQuickPricerForLockDesk__return = port.runQuickPricerForLockDesk(_runQuickPricerForLockDesk_sTicket, _runQuickPricerForLockDesk_sXmlData);
        System.out.println("runQuickPricerForLockDesk.result=" + _runQuickPricerForLockDesk__return);


        }
        {
        System.out.println("Invoking registerLoanProgram...");
        java.lang.String _registerLoanProgram_sTicket = "_registerLoanProgram_sTicket-650730290";
        java.lang.String _registerLoanProgram_sLNm = "_registerLoanProgram_sLNm-71406823";
        java.lang.String _registerLoanProgram_lLpTemplateId = "_registerLoanProgram_lLpTemplateId783938918";
        java.math.BigDecimal _registerLoanProgram_requestedRate = new java.math.BigDecimal("-8849714478697031908.5240964559802152848");
        java.math.BigDecimal _registerLoanProgram_requestedFee = new java.math.BigDecimal("8914212553370054489.1544013952080241160");
        java.lang.String _registerLoanProgram__return = port.registerLoanProgram(_registerLoanProgram_sTicket, _registerLoanProgram_sLNm, _registerLoanProgram_lLpTemplateId, _registerLoanProgram_requestedRate, _registerLoanProgram_requestedFee);
        System.out.println("registerLoanProgram.result=" + _registerLoanProgram__return);


        }
        {
        System.out.println("Invoking uploadPDFDocumentToApp...");
        java.lang.String _uploadPDFDocumentToApp_sTicket = "_uploadPDFDocumentToApp_sTicket1146139413";
        java.lang.String _uploadPDFDocumentToApp_sLNm = "_uploadPDFDocumentToApp_sLNm1249974132";
        java.lang.String _uploadPDFDocumentToApp_aAppId = "_uploadPDFDocumentToApp_aAppId-925673313";
        java.lang.String _uploadPDFDocumentToApp_documentType = "_uploadPDFDocumentToApp_documentType1467871243";
        java.lang.String _uploadPDFDocumentToApp_notes = "_uploadPDFDocumentToApp_notes-264080833";
        java.lang.String _uploadPDFDocumentToApp_sDataContent = "_uploadPDFDocumentToApp_sDataContent829718841";
        java.lang.String _uploadPDFDocumentToApp__return = port.uploadPDFDocumentToApp(_uploadPDFDocumentToApp_sTicket, _uploadPDFDocumentToApp_sLNm, _uploadPDFDocumentToApp_aAppId, _uploadPDFDocumentToApp_documentType, _uploadPDFDocumentToApp_notes, _uploadPDFDocumentToApp_sDataContent);
        System.out.println("uploadPDFDocumentToApp.result=" + _uploadPDFDocumentToApp__return);


        }
        {
        System.out.println("Invoking retrieveTaskById...");
        java.lang.String _retrieveTaskById_sTicket = "_retrieveTaskById_sTicket-522461397";
        java.lang.String _retrieveTaskById_taskId = "_retrieveTaskById_taskId-1742654815";
        java.lang.String _retrieveTaskById__return = port.retrieveTaskById(_retrieveTaskById_sTicket, _retrieveTaskById_taskId);
        System.out.println("retrieveTaskById.result=" + _retrieveTaskById__return);


        }
        {
        System.out.println("Invoking checkValidAppStatus...");
        java.lang.String _checkValidAppStatus_appName = "_checkValidAppStatus_appName-624527552";
        java.lang.String _checkValidAppStatus_appVersion = "_checkValidAppStatus_appVersion-1090430402";
        java.lang.String _checkValidAppStatus__return = port.checkValidAppStatus(_checkValidAppStatus_appName, _checkValidAppStatus_appVersion);
        System.out.println("checkValidAppStatus.result=" + _checkValidAppStatus__return);


        }
        {
        System.out.println("Invoking submitToLoanProspectorSeamless...");
        java.lang.String _submitToLoanProspectorSeamless_sTicket = "_submitToLoanProspectorSeamless_sTicket-602857118";
        java.lang.String _submitToLoanProspectorSeamless_sLNm = "_submitToLoanProspectorSeamless_sLNm1319169221";
        java.lang.String _submitToLoanProspectorSeamless_lpUserId = "_submitToLoanProspectorSeamless_lpUserId-1197563155";
        java.lang.String _submitToLoanProspectorSeamless_lpPassword = "_submitToLoanProspectorSeamless_lpPassword1163385346";
        java.lang.String _submitToLoanProspectorSeamless_creditMethod = "_submitToLoanProspectorSeamless_creditMethod692333248";
        java.lang.String _submitToLoanProspectorSeamless_craProvider = "_submitToLoanProspectorSeamless_craProvider-940812028";
        java.lang.String _submitToLoanProspectorSeamless_borrowerCreditInfoXml = "_submitToLoanProspectorSeamless_borrowerCreditInfoXml-118820423";
        java.lang.String _submitToLoanProspectorSeamless__return = port.submitToLoanProspectorSeamless(_submitToLoanProspectorSeamless_sTicket, _submitToLoanProspectorSeamless_sLNm, _submitToLoanProspectorSeamless_lpUserId, _submitToLoanProspectorSeamless_lpPassword, _submitToLoanProspectorSeamless_creditMethod, _submitToLoanProspectorSeamless_craProvider, _submitToLoanProspectorSeamless_borrowerCreditInfoXml);
        System.out.println("submitToLoanProspectorSeamless.result=" + _submitToLoanProspectorSeamless__return);


        }
        {
        System.out.println("Invoking listMyActiveTaskList...");
        java.lang.String _listMyActiveTaskList_sTicket = "_listMyActiveTaskList_sTicket-841347502";
        java.lang.String _listMyActiveTaskList__return = port.listMyActiveTaskList(_listMyActiveTaskList_sTicket);
        System.out.println("listMyActiveTaskList.result=" + _listMyActiveTaskList__return);


        }
        {
        System.out.println("Invoking retrieveLoanActivityList...");
        java.lang.String _retrieveLoanActivityList_sTicket = "_retrieveLoanActivityList_sTicket-1448373361";
        java.lang.String _retrieveLoanActivityList_sLNm = "_retrieveLoanActivityList_sLNm-921000316";
        int _retrieveLoanActivityList_version = -580235667;
        java.lang.String _retrieveLoanActivityList__return = port.retrieveLoanActivityList(_retrieveLoanActivityList_sTicket, _retrieveLoanActivityList_sLNm, _retrieveLoanActivityList_version);
        System.out.println("retrieveLoanActivityList.result=" + _retrieveLoanActivityList__return);


        }
        {
        System.out.println("Invoking uploadLONXml...");
        java.lang.String _uploadLONXml_sTicket = "_uploadLONXml_sTicket-833042";
        java.lang.String _uploadLONXml_loanId = "_uploadLONXml_loanId-1087048511";
        java.lang.String _uploadLONXml_sXmlData = "_uploadLONXml_sXmlData1973011015";
        java.lang.String _uploadLONXml__return = port.uploadLONXml(_uploadLONXml_sTicket, _uploadLONXml_loanId, _uploadLONXml_sXmlData);
        System.out.println("uploadLONXml.result=" + _uploadLONXml__return);


        }
        {
        System.out.println("Invoking clearModifiedLoansList...");
        java.lang.String _clearModifiedLoansList_sTicket = "_clearModifiedLoansList_sTicket132733975";
        javax.xml.datatype.XMLGregorianCalendar _clearModifiedLoansList_lastModifiedDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-02-12T20:37:58.710+05:30");
        port.clearModifiedLoansList(_clearModifiedLoansList_sTicket, _clearModifiedLoansList_lastModifiedDate);


        }
        {
        System.out.println("Invoking lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck...");
        java.lang.String _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket = "_lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket-1482335891";
        java.lang.String _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm = "_lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm-296139521";
        java.lang.String _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId = "_lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId682225841";
        java.math.BigDecimal _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedRate = new java.math.BigDecimal("2125535485164626525.5246285644871042233");
        java.math.BigDecimal _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedFee = new java.math.BigDecimal("-8248045404428267347.4001959680963770041");
        java.lang.String _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId = "_lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId894632357";
        boolean _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_skipDuplicateCheck = false;
        java.lang.String _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck__return = port.lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck(_lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedRate, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedFee, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_skipDuplicateCheck);
        System.out.println("lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck.result=" + _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck__return);


        }
        {
        System.out.println("Invoking retrieveCustomReport...");
        java.lang.String _retrieveCustomReport_sTicket = "_retrieveCustomReport_sTicket1820861993";
        java.lang.String _retrieveCustomReport_sQueryNm = "_retrieveCustomReport_sQueryNm1880810786";
        boolean _retrieveCustomReport_includeAllWithAccess = false;
        java.lang.String _retrieveCustomReport__return = port.retrieveCustomReport(_retrieveCustomReport_sTicket, _retrieveCustomReport_sQueryNm, _retrieveCustomReport_includeAllWithAccess);
        System.out.println("retrieveCustomReport.result=" + _retrieveCustomReport__return);


        }
        {
        System.out.println("Invoking submitToDesktopOriginator...");
        java.lang.String _submitToDesktopOriginator_sTicket = "_submitToDesktopOriginator_sTicket350175513";
        java.lang.String _submitToDesktopOriginator_sLNm = "_submitToDesktopOriginator_sLNm-1621002381";
        java.lang.String _submitToDesktopOriginator_doUserName = "_submitToDesktopOriginator_doUserName1169275021";
        java.lang.String _submitToDesktopOriginator_doPassword = "_submitToDesktopOriginator_doPassword1029320190";
        java.lang.String _submitToDesktopOriginator__return = port.submitToDesktopOriginator(_submitToDesktopOriginator_sTicket, _submitToDesktopOriginator_sLNm, _submitToDesktopOriginator_doUserName, _submitToDesktopOriginator_doPassword);
        System.out.println("submitToDesktopOriginator.result=" + _submitToDesktopOriginator__return);


        }
        {
        System.out.println("Invoking retrieveUsersAssignedToLoan...");
        java.lang.String _retrieveUsersAssignedToLoan_sTicket = "_retrieveUsersAssignedToLoan_sTicket1344973548";
        java.lang.String _retrieveUsersAssignedToLoan_sLNm = "_retrieveUsersAssignedToLoan_sLNm450486322";
        java.lang.String _retrieveUsersAssignedToLoan__return = port.retrieveUsersAssignedToLoan(_retrieveUsersAssignedToLoan_sTicket, _retrieveUsersAssignedToLoan_sLNm);
        System.out.println("retrieveUsersAssignedToLoan.result=" + _retrieveUsersAssignedToLoan__return);


        }
        {
        System.out.println("Invoking search...");
        java.lang.String _search_sTicket = "_search_sTicket85096891";
        java.lang.String _search_sSearchFilterXml = "_search_sSearchFilterXml1131557464";
        java.lang.String _search__return = port.search(_search_sTicket, _search_sSearchFilterXml);
        System.out.println("search.result=" + _search__return);


        }
        {
        System.out.println("Invoking submitToDesktopUnderwriter...");
        java.lang.String _submitToDesktopUnderwriter_sTicket = "_submitToDesktopUnderwriter_sTicket1533593623";
        java.lang.String _submitToDesktopUnderwriter_sLNm = "_submitToDesktopUnderwriter_sLNm-1206253042";
        java.lang.String _submitToDesktopUnderwriter_duUserName = "_submitToDesktopUnderwriter_duUserName-1946904798";
        java.lang.String _submitToDesktopUnderwriter_duPassword = "_submitToDesktopUnderwriter_duPassword1847391085";
        java.lang.String _submitToDesktopUnderwriter__return = port.submitToDesktopUnderwriter(_submitToDesktopUnderwriter_sTicket, _submitToDesktopUnderwriter_sLNm, _submitToDesktopUnderwriter_duUserName, _submitToDesktopUnderwriter_duPassword);
        System.out.println("submitToDesktopUnderwriter.result=" + _submitToDesktopUnderwriter__return);


        }
        {
        System.out.println("Invoking listModifiedLoansByAppCode...");
        java.lang.String _listModifiedLoansByAppCode_sTicket = "_listModifiedLoansByAppCode_sTicket-1594353667";
        java.lang.String _listModifiedLoansByAppCode_appCode = "_listModifiedLoansByAppCode_appCode-167044369";
        java.lang.String _listModifiedLoansByAppCode__return = port.listModifiedLoansByAppCode(_listModifiedLoansByAppCode_sTicket, _listModifiedLoansByAppCode_appCode);
        System.out.println("listModifiedLoansByAppCode.result=" + _listModifiedLoansByAppCode__return);


        }
        {
        System.out.println("Invoking clearModifiedLoanByName...");
        java.lang.String _clearModifiedLoanByName_sTicket = "_clearModifiedLoanByName_sTicket402759737";
        java.lang.String _clearModifiedLoanByName_loanName = "_clearModifiedLoanByName_loanName-1147819308";
        port.clearModifiedLoanByName(_clearModifiedLoanByName_sTicket, _clearModifiedLoanByName_loanName);


        }

        System.exit(0);
    }

}
