
package com.lendersoffice.los.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-02-12T20:37:58.482+05:30
 * Generated source version: 2.6.16
 * 
 */
public final class LoanSoap_LoanSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.lendersoffice.com/los/webservices/", "Loan");

    private LoanSoap_LoanSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Loan.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Loan ss = new Loan(wsdlURL, SERVICE_NAME);
        LoanSoap port = ss.getLoanSoap();  
        
        {
        System.out.println("Invoking save...");
        java.lang.String _save_sTicket = "_save_sTicket1661491878";
        java.lang.String _save_sLNm = "_save_sLNm1748604619";
        java.lang.String _save_sDataContent = "_save_sDataContent276228291";
        int _save_format = 1454721721;
        java.lang.String _save__return = port.save(_save_sTicket, _save_sLNm, _save_sDataContent, _save_format);
        System.out.println("save.result=" + _save__return);


        }
        {
        System.out.println("Invoking loadMismo23ByLoanName...");
        java.lang.String _loadMismo23ByLoanName_sTicket = "_loadMismo23ByLoanName_sTicket1154195495";
        java.lang.String _loadMismo23ByLoanName_sLNm = "_loadMismo23ByLoanName_sLNm-226175743";
        java.lang.String _loadMismo23ByLoanName_sXmlQuery = "_loadMismo23ByLoanName_sXmlQuery964294774";
        java.lang.String _loadMismo23ByLoanName__return = port.loadMismo23ByLoanName(_loadMismo23ByLoanName_sTicket, _loadMismo23ByLoanName_sLNm, _loadMismo23ByLoanName_sXmlQuery);
        System.out.println("loadMismo23ByLoanName.result=" + _loadMismo23ByLoanName__return);


        }
        {
        System.out.println("Invoking deleteLoan...");
        java.lang.String _deleteLoan_sTicket = "_deleteLoan_sTicket458080635";
        java.lang.String _deleteLoan_sLNm = "_deleteLoan_sLNm1869335621";
        java.lang.String _deleteLoan__return = port.deleteLoan(_deleteLoan_sTicket, _deleteLoan_sLNm);
        System.out.println("deleteLoan.result=" + _deleteLoan__return);


        }
        {
        System.out.println("Invoking breakBrokerRateLock...");
        java.lang.String _breakBrokerRateLock_sTicket = "_breakBrokerRateLock_sTicket-1760985117";
        java.lang.String _breakBrokerRateLock_sLNm = "_breakBrokerRateLock_sLNm-924018607";
        java.lang.String _breakBrokerRateLock_reason = "_breakBrokerRateLock_reason25721682";
        java.lang.String _breakBrokerRateLock__return = port.breakBrokerRateLock(_breakBrokerRateLock_sTicket, _breakBrokerRateLock_sLNm, _breakBrokerRateLock_reason);
        System.out.println("breakBrokerRateLock.result=" + _breakBrokerRateLock__return);


        }
        {
        System.out.println("Invoking submitTotalScorecard...");
        java.lang.String _submitTotalScorecard_sTicket = "_submitTotalScorecard_sTicket1046105261";
        java.lang.String _submitTotalScorecard_sLNm = "_submitTotalScorecard_sLNm-1708309987";
        java.lang.String _submitTotalScorecard__return = port.submitTotalScorecard(_submitTotalScorecard_sTicket, _submitTotalScorecard_sLNm);
        System.out.println("submitTotalScorecard.result=" + _submitTotalScorecard__return);


        }
        {
        System.out.println("Invoking lockLoanProgramWithRateOptionId...");
        java.lang.String _lockLoanProgramWithRateOptionId_sTicket = "_lockLoanProgramWithRateOptionId_sTicket972229212";
        java.lang.String _lockLoanProgramWithRateOptionId_sLNm = "_lockLoanProgramWithRateOptionId_sLNm875211880";
        java.lang.String _lockLoanProgramWithRateOptionId_lLpTemplateId = "_lockLoanProgramWithRateOptionId_lLpTemplateId454816255";
        java.math.BigDecimal _lockLoanProgramWithRateOptionId_requestedRate = new java.math.BigDecimal("3769386439966104697.6928356098719745201");
        java.math.BigDecimal _lockLoanProgramWithRateOptionId_requestedFee = new java.math.BigDecimal("3982402059900821993.6256979284900267060");
        java.lang.String _lockLoanProgramWithRateOptionId_rateOptionId = "_lockLoanProgramWithRateOptionId_rateOptionId1662324466";
        java.lang.String _lockLoanProgramWithRateOptionId__return = port.lockLoanProgramWithRateOptionId(_lockLoanProgramWithRateOptionId_sTicket, _lockLoanProgramWithRateOptionId_sLNm, _lockLoanProgramWithRateOptionId_lLpTemplateId, _lockLoanProgramWithRateOptionId_requestedRate, _lockLoanProgramWithRateOptionId_requestedFee, _lockLoanProgramWithRateOptionId_rateOptionId);
        System.out.println("lockLoanProgramWithRateOptionId.result=" + _lockLoanProgramWithRateOptionId__return);


        }
        {
        System.out.println("Invoking runInternalPricing...");
        java.lang.String _runInternalPricing_sTicket = "_runInternalPricing_sTicket623771924";
        java.lang.String _runInternalPricing_sLNm = "_runInternalPricing_sLNm1248176459";
        java.lang.String _runInternalPricing_sXmlData = "_runInternalPricing_sXmlData-1620626348";
        java.lang.String _runInternalPricing__return = port.runInternalPricing(_runInternalPricing_sTicket, _runInternalPricing_sLNm, _runInternalPricing_sXmlData);
        System.out.println("runInternalPricing.result=" + _runInternalPricing__return);


        }
        {
        System.out.println("Invoking lockLoanProgramAndSkipDuplicateCheck...");
        java.lang.String _lockLoanProgramAndSkipDuplicateCheck_sTicket = "_lockLoanProgramAndSkipDuplicateCheck_sTicket-1238993453";
        java.lang.String _lockLoanProgramAndSkipDuplicateCheck_sLNm = "_lockLoanProgramAndSkipDuplicateCheck_sLNm-2142054007";
        java.lang.String _lockLoanProgramAndSkipDuplicateCheck_lLpTemplateId = "_lockLoanProgramAndSkipDuplicateCheck_lLpTemplateId-1898984447";
        java.math.BigDecimal _lockLoanProgramAndSkipDuplicateCheck_requestedRate = new java.math.BigDecimal("-7232678869118549660.7160167338365015480");
        java.math.BigDecimal _lockLoanProgramAndSkipDuplicateCheck_requestedFee = new java.math.BigDecimal("-5199300659759608484.7050244672716933967");
        boolean _lockLoanProgramAndSkipDuplicateCheck_skipDuplicateCheck = false;
        java.lang.String _lockLoanProgramAndSkipDuplicateCheck__return = port.lockLoanProgramAndSkipDuplicateCheck(_lockLoanProgramAndSkipDuplicateCheck_sTicket, _lockLoanProgramAndSkipDuplicateCheck_sLNm, _lockLoanProgramAndSkipDuplicateCheck_lLpTemplateId, _lockLoanProgramAndSkipDuplicateCheck_requestedRate, _lockLoanProgramAndSkipDuplicateCheck_requestedFee, _lockLoanProgramAndSkipDuplicateCheck_skipDuplicateCheck);
        System.out.println("lockLoanProgramAndSkipDuplicateCheck.result=" + _lockLoanProgramAndSkipDuplicateCheck__return);


        }
        {
        System.out.println("Invoking parseFnma32ToLoXml...");
        java.lang.String _parseFnma32ToLoXml_sTicket = "_parseFnma32ToLoXml_sTicket-300347055";
        java.lang.String _parseFnma32ToLoXml_fnma32Content = "_parseFnma32ToLoXml_fnma32Content737993959";
        java.lang.String _parseFnma32ToLoXml_sXmlQuery = "_parseFnma32ToLoXml_sXmlQuery-1480408091";
        java.lang.String _parseFnma32ToLoXml__return = port.parseFnma32ToLoXml(_parseFnma32ToLoXml_sTicket, _parseFnma32ToLoXml_fnma32Content, _parseFnma32ToLoXml_sXmlQuery);
        System.out.println("parseFnma32ToLoXml.result=" + _parseFnma32ToLoXml__return);


        }
        {
        System.out.println("Invoking submitToDesktopUnderwriterSeamless...");
        java.lang.String _submitToDesktopUnderwriterSeamless_sTicket = "_submitToDesktopUnderwriterSeamless_sTicket-1102333207";
        java.lang.String _submitToDesktopUnderwriterSeamless_sLNm = "_submitToDesktopUnderwriterSeamless_sLNm444168518";
        java.lang.String _submitToDesktopUnderwriterSeamless_duUserName = "_submitToDesktopUnderwriterSeamless_duUserName-1695177270";
        java.lang.String _submitToDesktopUnderwriterSeamless_duPassword = "_submitToDesktopUnderwriterSeamless_duPassword-1636301430";
        java.lang.String _submitToDesktopUnderwriterSeamless_institutionId = "_submitToDesktopUnderwriterSeamless_institutionId-887429899";
        java.lang.String _submitToDesktopUnderwriterSeamless_craProvider = "_submitToDesktopUnderwriterSeamless_craProvider-540871801";
        java.lang.String _submitToDesktopUnderwriterSeamless_craLoginName = "_submitToDesktopUnderwriterSeamless_craLoginName-831741143";
        java.lang.String _submitToDesktopUnderwriterSeamless_craPassword = "_submitToDesktopUnderwriterSeamless_craPassword720746809";
        boolean _submitToDesktopUnderwriterSeamless_isCopyLiabilities = true;
        java.lang.String _submitToDesktopUnderwriterSeamless__return = port.submitToDesktopUnderwriterSeamless(_submitToDesktopUnderwriterSeamless_sTicket, _submitToDesktopUnderwriterSeamless_sLNm, _submitToDesktopUnderwriterSeamless_duUserName, _submitToDesktopUnderwriterSeamless_duPassword, _submitToDesktopUnderwriterSeamless_institutionId, _submitToDesktopUnderwriterSeamless_craProvider, _submitToDesktopUnderwriterSeamless_craLoginName, _submitToDesktopUnderwriterSeamless_craPassword, _submitToDesktopUnderwriterSeamless_isCopyLiabilities);
        System.out.println("submitToDesktopUnderwriterSeamless.result=" + _submitToDesktopUnderwriterSeamless__return);


        }
        {
        System.out.println("Invoking submitToDesktopUnderwriterWithInstituteId...");
        java.lang.String _submitToDesktopUnderwriterWithInstituteId_sTicket = "_submitToDesktopUnderwriterWithInstituteId_sTicket-821737543";
        java.lang.String _submitToDesktopUnderwriterWithInstituteId_sLNm = "_submitToDesktopUnderwriterWithInstituteId_sLNm1880209369";
        java.lang.String _submitToDesktopUnderwriterWithInstituteId_duUserName = "_submitToDesktopUnderwriterWithInstituteId_duUserName639150598";
        java.lang.String _submitToDesktopUnderwriterWithInstituteId_duPassword = "_submitToDesktopUnderwriterWithInstituteId_duPassword-2025351923";
        java.lang.String _submitToDesktopUnderwriterWithInstituteId_institutionId = "_submitToDesktopUnderwriterWithInstituteId_institutionId1457654572";
        java.lang.String _submitToDesktopUnderwriterWithInstituteId__return = port.submitToDesktopUnderwriterWithInstituteId(_submitToDesktopUnderwriterWithInstituteId_sTicket, _submitToDesktopUnderwriterWithInstituteId_sLNm, _submitToDesktopUnderwriterWithInstituteId_duUserName, _submitToDesktopUnderwriterWithInstituteId_duPassword, _submitToDesktopUnderwriterWithInstituteId_institutionId);
        System.out.println("submitToDesktopUnderwriterWithInstituteId.result=" + _submitToDesktopUnderwriterWithInstituteId__return);


        }
        {
        System.out.println("Invoking uploadPDFDocument...");
        java.lang.String _uploadPDFDocument_sTicket = "_uploadPDFDocument_sTicket-1733691148";
        java.lang.String _uploadPDFDocument_sLNm = "_uploadPDFDocument_sLNm-309607533";
        java.lang.String _uploadPDFDocument_documentType = "_uploadPDFDocument_documentType1502988350";
        java.lang.String _uploadPDFDocument_notes = "_uploadPDFDocument_notes1518585460";
        java.lang.String _uploadPDFDocument_sDataContent = "_uploadPDFDocument_sDataContent528330201";
        java.lang.String _uploadPDFDocument__return = port.uploadPDFDocument(_uploadPDFDocument_sTicket, _uploadPDFDocument_sLNm, _uploadPDFDocument_documentType, _uploadPDFDocument_notes, _uploadPDFDocument_sDataContent);
        System.out.println("uploadPDFDocument.result=" + _uploadPDFDocument__return);


        }
        {
        System.out.println("Invoking clearModifiedLoanByNameByAppCode...");
        java.lang.String _clearModifiedLoanByNameByAppCode_sTicket = "_clearModifiedLoanByNameByAppCode_sTicket505299912";
        java.lang.String _clearModifiedLoanByNameByAppCode_loanName = "_clearModifiedLoanByNameByAppCode_loanName-118850029";
        java.lang.String _clearModifiedLoanByNameByAppCode_appCode = "_clearModifiedLoanByNameByAppCode_appCode812212279";
        port.clearModifiedLoanByNameByAppCode(_clearModifiedLoanByNameByAppCode_sTicket, _clearModifiedLoanByNameByAppCode_loanName, _clearModifiedLoanByNameByAppCode_appCode);


        }
        {
        System.out.println("Invoking submitToFannieMaeEarlyCheck...");
        java.lang.String _submitToFannieMaeEarlyCheck_sTicket = "_submitToFannieMaeEarlyCheck_sTicket744440950";
        java.lang.String _submitToFannieMaeEarlyCheck_sLNm = "_submitToFannieMaeEarlyCheck_sLNm652137410";
        java.lang.String _submitToFannieMaeEarlyCheck_duUserName = "_submitToFannieMaeEarlyCheck_duUserName2141819270";
        java.lang.String _submitToFannieMaeEarlyCheck_duPassword = "_submitToFannieMaeEarlyCheck_duPassword-218308281";
        java.lang.String _submitToFannieMaeEarlyCheck_institutionId = "_submitToFannieMaeEarlyCheck_institutionId376882633";
        java.lang.String _submitToFannieMaeEarlyCheck__return = port.submitToFannieMaeEarlyCheck(_submitToFannieMaeEarlyCheck_sTicket, _submitToFannieMaeEarlyCheck_sLNm, _submitToFannieMaeEarlyCheck_duUserName, _submitToFannieMaeEarlyCheck_duPassword, _submitToFannieMaeEarlyCheck_institutionId);
        System.out.println("submitToFannieMaeEarlyCheck.result=" + _submitToFannieMaeEarlyCheck__return);


        }
        {
        System.out.println("Invoking getPdfByLoanName...");
        java.lang.String _getPdfByLoanName_sTicket = "_getPdfByLoanName_sTicket-769999860";
        java.lang.String _getPdfByLoanName_sLNm = "_getPdfByLoanName_sLNm1568283067";
        java.lang.String _getPdfByLoanName_sPdfName = "_getPdfByLoanName_sPdfName-859183630";
        java.lang.String _getPdfByLoanName__return = port.getPdfByLoanName(_getPdfByLoanName_sTicket, _getPdfByLoanName_sLNm, _getPdfByLoanName_sPdfName);
        System.out.println("getPdfByLoanName.result=" + _getPdfByLoanName__return);


        }
        {
        System.out.println("Invoking registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck...");
        java.lang.String _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket = "_registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket313626275";
        java.lang.String _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm = "_registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm933210124";
        java.lang.String _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId = "_registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId1506859618";
        java.math.BigDecimal _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedRate = new java.math.BigDecimal("-4424416540377591634.4714797398876563873");
        java.math.BigDecimal _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedFee = new java.math.BigDecimal("-2018437819659608142.8939230366044252333");
        java.lang.String _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId = "_registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId1211111394";
        boolean _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_skipDuplicateCheck = false;
        java.lang.String _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck__return = port.registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck(_registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedRate, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedFee, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId, _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck_skipDuplicateCheck);
        System.out.println("registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck.result=" + _registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck__return);


        }
        {
        System.out.println("Invoking registerLoanProgramWithRateOptionId...");
        java.lang.String _registerLoanProgramWithRateOptionId_sTicket = "_registerLoanProgramWithRateOptionId_sTicket569524997";
        java.lang.String _registerLoanProgramWithRateOptionId_sLNm = "_registerLoanProgramWithRateOptionId_sLNm-551581825";
        java.lang.String _registerLoanProgramWithRateOptionId_lLpTemplateId = "_registerLoanProgramWithRateOptionId_lLpTemplateId-1361330097";
        java.math.BigDecimal _registerLoanProgramWithRateOptionId_requestedRate = new java.math.BigDecimal("6690980828968699972.6996365830062953522");
        java.math.BigDecimal _registerLoanProgramWithRateOptionId_requestedFee = new java.math.BigDecimal("-5713768836478864972.6891464258479681196");
        java.lang.String _registerLoanProgramWithRateOptionId_rateOptionId = "_registerLoanProgramWithRateOptionId_rateOptionId1047256741";
        java.lang.String _registerLoanProgramWithRateOptionId__return = port.registerLoanProgramWithRateOptionId(_registerLoanProgramWithRateOptionId_sTicket, _registerLoanProgramWithRateOptionId_sLNm, _registerLoanProgramWithRateOptionId_lLpTemplateId, _registerLoanProgramWithRateOptionId_requestedRate, _registerLoanProgramWithRateOptionId_requestedFee, _registerLoanProgramWithRateOptionId_rateOptionId);
        System.out.println("registerLoanProgramWithRateOptionId.result=" + _registerLoanProgramWithRateOptionId__return);


        }
        {
        System.out.println("Invoking lockLoanProgram...");
        java.lang.String _lockLoanProgram_sTicket = "_lockLoanProgram_sTicket1054683775";
        java.lang.String _lockLoanProgram_sLNm = "_lockLoanProgram_sLNm1753306741";
        java.lang.String _lockLoanProgram_lLpTemplateId = "_lockLoanProgram_lLpTemplateId-1769710935";
        java.math.BigDecimal _lockLoanProgram_requestedRate = new java.math.BigDecimal("-8737984854480587816.3845051694949089744");
        java.math.BigDecimal _lockLoanProgram_requestedFee = new java.math.BigDecimal("-3792890925337206160.6679871106423249155");
        java.lang.String _lockLoanProgram__return = port.lockLoanProgram(_lockLoanProgram_sTicket, _lockLoanProgram_sLNm, _lockLoanProgram_lLpTemplateId, _lockLoanProgram_requestedRate, _lockLoanProgram_requestedFee);
        System.out.println("lockLoanProgram.result=" + _lockLoanProgram__return);


        }
        {
        System.out.println("Invoking importFromFannieMae...");
        java.lang.String _importFromFannieMae_sTicket = "_importFromFannieMae_sTicket-697048110";
        java.lang.String _importFromFannieMae_sLNm = "_importFromFannieMae_sLNm-1521115347";
        java.lang.String _importFromFannieMae_doUserName = "_importFromFannieMae_doUserName783712328";
        java.lang.String _importFromFannieMae_doPassword = "_importFromFannieMae_doPassword-420590516";
        boolean _importFromFannieMae_isImportCredit = true;
        java.lang.String _importFromFannieMae__return = port.importFromFannieMae(_importFromFannieMae_sTicket, _importFromFannieMae_sLNm, _importFromFannieMae_doUserName, _importFromFannieMae_doPassword, _importFromFannieMae_isImportCredit);
        System.out.println("importFromFannieMae.result=" + _importFromFannieMae__return);


        }
        {
        System.out.println("Invoking retrieveRecentActiveLoanList...");
        java.lang.String _retrieveRecentActiveLoanList_sTicket = "_retrieveRecentActiveLoanList_sTicket-301955299";
        java.lang.String _retrieveRecentActiveLoanList__return = port.retrieveRecentActiveLoanList(_retrieveRecentActiveLoanList_sTicket);
        System.out.println("retrieveRecentActiveLoanList.result=" + _retrieveRecentActiveLoanList__return);


        }
        {
        System.out.println("Invoking retrievePmlLoanList...");
        java.lang.String _retrievePmlLoanList_sTicket = "_retrievePmlLoanList_sTicket109254289";
        java.lang.String _retrievePmlLoanList__return = port.retrievePmlLoanList(_retrievePmlLoanList_sTicket);
        System.out.println("retrievePmlLoanList.result=" + _retrievePmlLoanList__return);


        }
        {
        System.out.println("Invoking clearModifiedLoansListByAppCode...");
        java.lang.String _clearModifiedLoansListByAppCode_sTicket = "_clearModifiedLoansListByAppCode_sTicket-1556276745";
        javax.xml.datatype.XMLGregorianCalendar _clearModifiedLoansListByAppCode_lastModifiedDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-02-12T20:37:58.583+05:30");
        java.lang.String _clearModifiedLoansListByAppCode_appCode = "_clearModifiedLoansListByAppCode_appCode-196882082";
        port.clearModifiedLoansListByAppCode(_clearModifiedLoansListByAppCode_sTicket, _clearModifiedLoansListByAppCode_lastModifiedDate, _clearModifiedLoansListByAppCode_appCode);


        }
        {
        System.out.println("Invoking removeRequestedRate...");
        java.lang.String _removeRequestedRate_sTicket = "_removeRequestedRate_sTicket-972847448";
        java.lang.String _removeRequestedRate_sLNm = "_removeRequestedRate_sLNm1197346448";
        java.lang.String _removeRequestedRate__return = port.removeRequestedRate(_removeRequestedRate_sTicket, _removeRequestedRate_sLNm);
        System.out.println("removeRequestedRate.result=" + _removeRequestedRate__return);


        }
        {
        System.out.println("Invoking recievePdf...");
        java.lang.String _recievePdf_authTicket = "_recievePdf_authTicket1577244867";
        java.lang.String _recievePdf_sLNm = "_recievePdf_sLNm-905740455";
        java.lang.String _recievePdf_documentClassification = "_recievePdf_documentClassification2073209861";
        java.lang.String _recievePdf_base64PdfContent = "_recievePdf_base64PdfContent2012100634";
        java.lang.String _recievePdf__return = port.recievePdf(_recievePdf_authTicket, _recievePdf_sLNm, _recievePdf_documentClassification, _recievePdf_base64PdfContent);
        System.out.println("recievePdf.result=" + _recievePdf__return);


        }
        {
        System.out.println("Invoking getDesktopUnderwriterCasefileStatus...");
        java.lang.String _getDesktopUnderwriterCasefileStatus_sTicket = "_getDesktopUnderwriterCasefileStatus_sTicket92473333";
        java.lang.String _getDesktopUnderwriterCasefileStatus_sDuCaseId = "_getDesktopUnderwriterCasefileStatus_sDuCaseId-1172946094";
        java.lang.String _getDesktopUnderwriterCasefileStatus_duUserName = "_getDesktopUnderwriterCasefileStatus_duUserName1172139247";
        java.lang.String _getDesktopUnderwriterCasefileStatus_duPassword = "_getDesktopUnderwriterCasefileStatus_duPassword-1352375963";
        boolean _getDesktopUnderwriterCasefileStatus_isDo = false;
        java.lang.String _getDesktopUnderwriterCasefileStatus__return = port.getDesktopUnderwriterCasefileStatus(_getDesktopUnderwriterCasefileStatus_sTicket, _getDesktopUnderwriterCasefileStatus_sDuCaseId, _getDesktopUnderwriterCasefileStatus_duUserName, _getDesktopUnderwriterCasefileStatus_duPassword, _getDesktopUnderwriterCasefileStatus_isDo);
        System.out.println("getDesktopUnderwriterCasefileStatus.result=" + _getDesktopUnderwriterCasefileStatus__return);


        }
        {
        System.out.println("Invoking createWithULDD...");
        java.lang.String _createWithULDD_sTicket = "_createWithULDD_sTicket1868321817";
        java.lang.String _createWithULDD_xml = "_createWithULDD_xml-1384262761";
        java.lang.String _createWithULDD__return = port.createWithULDD(_createWithULDD_sTicket, _createWithULDD_xml);
        System.out.println("createWithULDD.result=" + _createWithULDD__return);


        }
        {
        System.out.println("Invoking prepareLoanForResubmission...");
        java.lang.String _prepareLoanForResubmission_sTicket = "_prepareLoanForResubmission_sTicket-131812625";
        java.lang.String _prepareLoanForResubmission_sLNm = "_prepareLoanForResubmission_sLNm-713123990";
        java.lang.String _prepareLoanForResubmission__return = port.prepareLoanForResubmission(_prepareLoanForResubmission_sTicket, _prepareLoanForResubmission_sLNm);
        System.out.println("prepareLoanForResubmission.result=" + _prepareLoanForResubmission__return);


        }
        {
        System.out.println("Invoking listEdocsByLoanNumber...");
        java.lang.String _listEdocsByLoanNumber_sTicket = "_listEdocsByLoanNumber_sTicket-1784369712";
        java.lang.String _listEdocsByLoanNumber_sLNm = "_listEdocsByLoanNumber_sLNm-478607652";
        java.lang.String _listEdocsByLoanNumber__return = port.listEdocsByLoanNumber(_listEdocsByLoanNumber_sTicket, _listEdocsByLoanNumber_sLNm);
        System.out.println("listEdocsByLoanNumber.result=" + _listEdocsByLoanNumber__return);


        }
        {
        System.out.println("Invoking retrieveClosingCostTemplateFeeList...");
        java.lang.String _retrieveClosingCostTemplateFeeList_sTicket = "_retrieveClosingCostTemplateFeeList_sTicket2102355359";
        java.lang.String _retrieveClosingCostTemplateFeeList_closingCostName = "_retrieveClosingCostTemplateFeeList_closingCostName1711189619";
        java.lang.String _retrieveClosingCostTemplateFeeList__return = port.retrieveClosingCostTemplateFeeList(_retrieveClosingCostTemplateFeeList_sTicket, _retrieveClosingCostTemplateFeeList_closingCostName);
        System.out.println("retrieveClosingCostTemplateFeeList.result=" + _retrieveClosingCostTemplateFeeList__return);


        }
        {
        System.out.println("Invoking createWithFannieMaeFile...");
        java.lang.String _createWithFannieMaeFile_sTicket = "_createWithFannieMaeFile_sTicket2069704365";
        java.lang.String _createWithFannieMaeFile_content = "_createWithFannieMaeFile_content1338220985";
        java.lang.String _createWithFannieMaeFile__return = port.createWithFannieMaeFile(_createWithFannieMaeFile_sTicket, _createWithFannieMaeFile_content);
        System.out.println("createWithFannieMaeFile.result=" + _createWithFannieMaeFile__return);


        }
        {
        System.out.println("Invoking isLoanExisted...");
        java.lang.String _isLoanExisted_sTicket = "_isLoanExisted_sTicket1453078313";
        java.lang.String _isLoanExisted_sLNm = "_isLoanExisted_sLNm108982106";
        boolean _isLoanExisted__return = port.isLoanExisted(_isLoanExisted_sTicket, _isLoanExisted_sLNm);
        System.out.println("isLoanExisted.result=" + _isLoanExisted__return);


        }
        {
        System.out.println("Invoking getDesktopUnderwriterCasefileStatusByLoanFile...");
        java.lang.String _getDesktopUnderwriterCasefileStatusByLoanFile_sTicket = "_getDesktopUnderwriterCasefileStatusByLoanFile_sTicket916536317";
        java.lang.String _getDesktopUnderwriterCasefileStatusByLoanFile_sLNm = "_getDesktopUnderwriterCasefileStatusByLoanFile_sLNm409964030";
        java.lang.String _getDesktopUnderwriterCasefileStatusByLoanFile_duUserName = "_getDesktopUnderwriterCasefileStatusByLoanFile_duUserName-11648842";
        java.lang.String _getDesktopUnderwriterCasefileStatusByLoanFile_duPassword = "_getDesktopUnderwriterCasefileStatusByLoanFile_duPassword1072553304";
        boolean _getDesktopUnderwriterCasefileStatusByLoanFile_isDo = true;
        java.lang.String _getDesktopUnderwriterCasefileStatusByLoanFile__return = port.getDesktopUnderwriterCasefileStatusByLoanFile(_getDesktopUnderwriterCasefileStatusByLoanFile_sTicket, _getDesktopUnderwriterCasefileStatusByLoanFile_sLNm, _getDesktopUnderwriterCasefileStatusByLoanFile_duUserName, _getDesktopUnderwriterCasefileStatusByLoanFile_duPassword, _getDesktopUnderwriterCasefileStatusByLoanFile_isDo);
        System.out.println("getDesktopUnderwriterCasefileStatusByLoanFile.result=" + _getDesktopUnderwriterCasefileStatusByLoanFile__return);


        }
        {
        System.out.println("Invoking saveMismo23...");
        java.lang.String _saveMismo23_sTicket = "_saveMismo23_sTicket1657820738";
        java.lang.String _saveMismo23_loanId = "_saveMismo23_loanId-650374205";
        java.lang.String _saveMismo23_sXmlData = "_saveMismo23_sXmlData1092924895";
        java.lang.String _saveMismo23__return = port.saveMismo23(_saveMismo23_sTicket, _saveMismo23_loanId, _saveMismo23_sXmlData);
        System.out.println("saveMismo23.result=" + _saveMismo23__return);


        }
        {
        System.out.println("Invoking deleteApplicant...");
        java.lang.String _deleteApplicant_sTicket = "_deleteApplicant_sTicket923610241";
        java.lang.String _deleteApplicant_sLNm = "_deleteApplicant_sLNm-1556208873";
        java.lang.String _deleteApplicant_applicantSSN = "_deleteApplicant_applicantSSN-700300984";
        java.lang.String _deleteApplicant__return = port.deleteApplicant(_deleteApplicant_sTicket, _deleteApplicant_sLNm, _deleteApplicant_applicantSSN);
        System.out.println("deleteApplicant.result=" + _deleteApplicant__return);


        }
        {
        System.out.println("Invoking importFromFannieMaeWithInstitutionId...");
        java.lang.String _importFromFannieMaeWithInstitutionId_sTicket = "_importFromFannieMaeWithInstitutionId_sTicket-1220193554";
        java.lang.String _importFromFannieMaeWithInstitutionId_sLNm = "_importFromFannieMaeWithInstitutionId_sLNm-1175859601";
        java.lang.String _importFromFannieMaeWithInstitutionId_doUserName = "_importFromFannieMaeWithInstitutionId_doUserName-168896641";
        java.lang.String _importFromFannieMaeWithInstitutionId_doPassword = "_importFromFannieMaeWithInstitutionId_doPassword791981853";
        java.lang.String _importFromFannieMaeWithInstitutionId_lenderInstitutionIdentifer = "_importFromFannieMaeWithInstitutionId_lenderInstitutionIdentifer-178037082";
        boolean _importFromFannieMaeWithInstitutionId_isImportCredit = false;
        java.lang.String _importFromFannieMaeWithInstitutionId__return = port.importFromFannieMaeWithInstitutionId(_importFromFannieMaeWithInstitutionId_sTicket, _importFromFannieMaeWithInstitutionId_sLNm, _importFromFannieMaeWithInstitutionId_doUserName, _importFromFannieMaeWithInstitutionId_doPassword, _importFromFannieMaeWithInstitutionId_lenderInstitutionIdentifer, _importFromFannieMaeWithInstitutionId_isImportCredit);
        System.out.println("importFromFannieMaeWithInstitutionId.result=" + _importFromFannieMaeWithInstitutionId__return);


        }
        {
        System.out.println("Invoking listModifiedEDocsByAppCode...");
        java.lang.String _listModifiedEDocsByAppCode_sTicket = "_listModifiedEDocsByAppCode_sTicket1725956255";
        java.lang.String _listModifiedEDocsByAppCode_appCode = "_listModifiedEDocsByAppCode_appCode1103454105";
        java.lang.String _listModifiedEDocsByAppCode_modifiedDate = "_listModifiedEDocsByAppCode_modifiedDate173321245";
        java.lang.String _listModifiedEDocsByAppCode__return = port.listModifiedEDocsByAppCode(_listModifiedEDocsByAppCode_sTicket, _listModifiedEDocsByAppCode_appCode, _listModifiedEDocsByAppCode_modifiedDate);
        System.out.println("listModifiedEDocsByAppCode.result=" + _listModifiedEDocsByAppCode__return);


        }
        {
        System.out.println("Invoking create...");
        java.lang.String _create_sTicket = "_create_sTicket283273241";
        java.lang.String _create_sTemplateNm = "_create_sTemplateNm1732480178";
        java.lang.String _create__return = port.create(_create_sTicket, _create_sTemplateNm);
        System.out.println("create.result=" + _create__return);


        }
        {
        System.out.println("Invoking createWithCalyxPointFile...");
        java.lang.String _createWithCalyxPointFile_sTicket = "_createWithCalyxPointFile_sTicket2099089276";
        java.lang.String _createWithCalyxPointFile_base64Content = "_createWithCalyxPointFile_base64Content1424869746";
        java.lang.String _createWithCalyxPointFile__return = port.createWithCalyxPointFile(_createWithCalyxPointFile_sTicket, _createWithCalyxPointFile_base64Content);
        System.out.println("createWithCalyxPointFile.result=" + _createWithCalyxPointFile__return);


        }
        {
        System.out.println("Invoking registerLoanProgramAndSkipDuplicateCheck...");
        java.lang.String _registerLoanProgramAndSkipDuplicateCheck_sTicket = "_registerLoanProgramAndSkipDuplicateCheck_sTicket-1344984117";
        java.lang.String _registerLoanProgramAndSkipDuplicateCheck_sLNm = "_registerLoanProgramAndSkipDuplicateCheck_sLNm-812876481";
        java.lang.String _registerLoanProgramAndSkipDuplicateCheck_lLpTemplateId = "_registerLoanProgramAndSkipDuplicateCheck_lLpTemplateId156257806";
        java.math.BigDecimal _registerLoanProgramAndSkipDuplicateCheck_requestedRate = new java.math.BigDecimal("4444242638246128010.8838304861417376889");
        java.math.BigDecimal _registerLoanProgramAndSkipDuplicateCheck_requestedFee = new java.math.BigDecimal("8802338900122483190.5817843298787518031");
        boolean _registerLoanProgramAndSkipDuplicateCheck_skipDuplicateCheck = true;
        java.lang.String _registerLoanProgramAndSkipDuplicateCheck__return = port.registerLoanProgramAndSkipDuplicateCheck(_registerLoanProgramAndSkipDuplicateCheck_sTicket, _registerLoanProgramAndSkipDuplicateCheck_sLNm, _registerLoanProgramAndSkipDuplicateCheck_lLpTemplateId, _registerLoanProgramAndSkipDuplicateCheck_requestedRate, _registerLoanProgramAndSkipDuplicateCheck_requestedFee, _registerLoanProgramAndSkipDuplicateCheck_skipDuplicateCheck);
        System.out.println("registerLoanProgramAndSkipDuplicateCheck.result=" + _registerLoanProgramAndSkipDuplicateCheck__return);


        }
        {
        System.out.println("Invoking runQuickPricer...");
        java.lang.String _runQuickPricer_sTicket = "_runQuickPricer_sTicket278384940";
        java.lang.String _runQuickPricer_sXmlData = "_runQuickPricer_sXmlData-981367875";
        java.lang.String _runQuickPricer__return = port.runQuickPricer(_runQuickPricer_sTicket, _runQuickPricer_sXmlData);
        System.out.println("runQuickPricer.result=" + _runQuickPricer__return);


        }
        {
        System.out.println("Invoking downloadEdocsByShippingTemplate...");
        java.lang.String _downloadEdocsByShippingTemplate_sTicket = "_downloadEdocsByShippingTemplate_sTicket-1072432437";
        java.lang.String _downloadEdocsByShippingTemplate_sShippingTemplateName = "_downloadEdocsByShippingTemplate_sShippingTemplateName-1460050046";
        java.lang.String _downloadEdocsByShippingTemplate_sLNm = "_downloadEdocsByShippingTemplate_sLNm2103235142";
        boolean _downloadEdocsByShippingTemplate_includeScreenedDocs = false;
        boolean _downloadEdocsByShippingTemplate_includeDocsWithoutStatus = false;
        byte[] _downloadEdocsByShippingTemplate__return = port.downloadEdocsByShippingTemplate(_downloadEdocsByShippingTemplate_sTicket, _downloadEdocsByShippingTemplate_sShippingTemplateName, _downloadEdocsByShippingTemplate_sLNm, _downloadEdocsByShippingTemplate_includeScreenedDocs, _downloadEdocsByShippingTemplate_includeDocsWithoutStatus);
        System.out.println("downloadEdocsByShippingTemplate.result=" + _downloadEdocsByShippingTemplate__return);


        }
        {
        System.out.println("Invoking taskResolve...");
        java.lang.String _taskResolve_sTicket = "_taskResolve_sTicket-1296531142";
        java.lang.String _taskResolve_taskId = "_taskResolve_taskId495687463";
        java.lang.String _taskResolve_subject = "_taskResolve_subject564930394";
        java.lang.String _taskResolve_comment = "_taskResolve_comment1093033529";
        java.lang.String _taskResolve_dueDate = "_taskResolve_dueDate672491821";
        java.lang.String _taskResolve_assignedTo = "_taskResolve_assignedTo359084151";
        java.lang.String _taskResolve__return = port.taskResolve(_taskResolve_sTicket, _taskResolve_taskId, _taskResolve_subject, _taskResolve_comment, _taskResolve_dueDate, _taskResolve_assignedTo);
        System.out.println("taskResolve.result=" + _taskResolve__return);


        }
        {
        System.out.println("Invoking taskEdit...");
        java.lang.String _taskEdit_sTicket = "_taskEdit_sTicket-1926648851";
        java.lang.String _taskEdit_taskId = "_taskEdit_taskId-1568738082";
        java.lang.String _taskEdit_subject = "_taskEdit_subject-741706262";
        java.lang.String _taskEdit_comment = "_taskEdit_comment-897900052";
        java.lang.String _taskEdit_dueDate = "_taskEdit_dueDate928327543";
        java.lang.String _taskEdit_assignedTo = "_taskEdit_assignedTo-419645277";
        java.lang.String _taskEdit__return = port.taskEdit(_taskEdit_sTicket, _taskEdit_taskId, _taskEdit_subject, _taskEdit_comment, _taskEdit_dueDate, _taskEdit_assignedTo);
        System.out.println("taskEdit.result=" + _taskEdit__return);


        }
        {
        System.out.println("Invoking createLead...");
        java.lang.String _createLead_sTicket = "_createLead_sTicket-1432668502";
        java.lang.String _createLead_sTemplateNm = "_createLead_sTemplateNm313466571";
        java.lang.String _createLead__return = port.createLead(_createLead_sTicket, _createLead_sTemplateNm);
        System.out.println("createLead.result=" + _createLead__return);


        }
        {
        System.out.println("Invoking downloadEdocsPdfById...");
        java.lang.String _downloadEdocsPdfById_sTicket = "_downloadEdocsPdfById_sTicket2138313515";
        java.lang.String _downloadEdocsPdfById_docId = "_downloadEdocsPdfById_docId1921673265";
        byte[] _downloadEdocsPdfById__return = port.downloadEdocsPdfById(_downloadEdocsPdfById_sTicket, _downloadEdocsPdfById_docId);
        System.out.println("downloadEdocsPdfById.result=" + _downloadEdocsPdfById__return);


        }
        {
        System.out.println("Invoking load...");
        java.lang.String _load_sTicket = "_load_sTicket29740197";
        java.lang.String _load_sLNm = "_load_sLNm1782287022";
        java.lang.String _load_sXmlQuery = "_load_sXmlQuery-256004712";
        int _load_format = 1671847746;
        java.lang.String _load__return = port.load(_load_sTicket, _load_sLNm, _load_sXmlQuery, _load_format);
        System.out.println("load.result=" + _load__return);


        }
        {
        System.out.println("Invoking listModifiedLoans...");
        java.lang.String _listModifiedLoans_sTicket = "_listModifiedLoans_sTicket-1558182496";
        java.lang.String _listModifiedLoans__return = port.listModifiedLoans(_listModifiedLoans_sTicket);
        System.out.println("listModifiedLoans.result=" + _listModifiedLoans__return);


        }
        {
        System.out.println("Invoking createWithDesktopUnderwriter...");
        java.lang.String _createWithDesktopUnderwriter_sTicket = "_createWithDesktopUnderwriter_sTicket-2107719033";
        java.lang.String _createWithDesktopUnderwriter_doUserName = "_createWithDesktopUnderwriter_doUserName-1395349149";
        java.lang.String _createWithDesktopUnderwriter_doPassword = "_createWithDesktopUnderwriter_doPassword1645719874";
        java.lang.String _createWithDesktopUnderwriter_sDuCaseId = "_createWithDesktopUnderwriter_sDuCaseId1297288138";
        boolean _createWithDesktopUnderwriter_isImportCredit = false;
        java.lang.String _createWithDesktopUnderwriter__return = port.createWithDesktopUnderwriter(_createWithDesktopUnderwriter_sTicket, _createWithDesktopUnderwriter_doUserName, _createWithDesktopUnderwriter_doPassword, _createWithDesktopUnderwriter_sDuCaseId, _createWithDesktopUnderwriter_isImportCredit);
        System.out.println("createWithDesktopUnderwriter.result=" + _createWithDesktopUnderwriter__return);


        }
        {
        System.out.println("Invoking listClosingCostTemplateName...");
        java.lang.String _listClosingCostTemplateName_sTicket = "_listClosingCostTemplateName_sTicket1486918454";
        java.lang.String _listClosingCostTemplateName__return = port.listClosingCostTemplateName(_listClosingCostTemplateName_sTicket);
        System.out.println("listClosingCostTemplateName.result=" + _listClosingCostTemplateName__return);


        }
        {
        System.out.println("Invoking runQuickPricerForLockDesk...");
        java.lang.String _runQuickPricerForLockDesk_sTicket = "_runQuickPricerForLockDesk_sTicket1577568819";
        java.lang.String _runQuickPricerForLockDesk_sXmlData = "_runQuickPricerForLockDesk_sXmlData578928328";
        java.lang.String _runQuickPricerForLockDesk__return = port.runQuickPricerForLockDesk(_runQuickPricerForLockDesk_sTicket, _runQuickPricerForLockDesk_sXmlData);
        System.out.println("runQuickPricerForLockDesk.result=" + _runQuickPricerForLockDesk__return);


        }
        {
        System.out.println("Invoking registerLoanProgram...");
        java.lang.String _registerLoanProgram_sTicket = "_registerLoanProgram_sTicket-1779926924";
        java.lang.String _registerLoanProgram_sLNm = "_registerLoanProgram_sLNm1971528440";
        java.lang.String _registerLoanProgram_lLpTemplateId = "_registerLoanProgram_lLpTemplateId1721416144";
        java.math.BigDecimal _registerLoanProgram_requestedRate = new java.math.BigDecimal("6328412958037582793.4032107317773110517");
        java.math.BigDecimal _registerLoanProgram_requestedFee = new java.math.BigDecimal("1592810199781785951.3267398913061837117");
        java.lang.String _registerLoanProgram__return = port.registerLoanProgram(_registerLoanProgram_sTicket, _registerLoanProgram_sLNm, _registerLoanProgram_lLpTemplateId, _registerLoanProgram_requestedRate, _registerLoanProgram_requestedFee);
        System.out.println("registerLoanProgram.result=" + _registerLoanProgram__return);


        }
        {
        System.out.println("Invoking uploadPDFDocumentToApp...");
        java.lang.String _uploadPDFDocumentToApp_sTicket = "_uploadPDFDocumentToApp_sTicket-1401871112";
        java.lang.String _uploadPDFDocumentToApp_sLNm = "_uploadPDFDocumentToApp_sLNm1415630044";
        java.lang.String _uploadPDFDocumentToApp_aAppId = "_uploadPDFDocumentToApp_aAppId-997760625";
        java.lang.String _uploadPDFDocumentToApp_documentType = "_uploadPDFDocumentToApp_documentType-409215252";
        java.lang.String _uploadPDFDocumentToApp_notes = "_uploadPDFDocumentToApp_notes-768526087";
        java.lang.String _uploadPDFDocumentToApp_sDataContent = "_uploadPDFDocumentToApp_sDataContent73481881";
        java.lang.String _uploadPDFDocumentToApp__return = port.uploadPDFDocumentToApp(_uploadPDFDocumentToApp_sTicket, _uploadPDFDocumentToApp_sLNm, _uploadPDFDocumentToApp_aAppId, _uploadPDFDocumentToApp_documentType, _uploadPDFDocumentToApp_notes, _uploadPDFDocumentToApp_sDataContent);
        System.out.println("uploadPDFDocumentToApp.result=" + _uploadPDFDocumentToApp__return);


        }
        {
        System.out.println("Invoking retrieveTaskById...");
        java.lang.String _retrieveTaskById_sTicket = "_retrieveTaskById_sTicket-1433290554";
        java.lang.String _retrieveTaskById_taskId = "_retrieveTaskById_taskId-531307249";
        java.lang.String _retrieveTaskById__return = port.retrieveTaskById(_retrieveTaskById_sTicket, _retrieveTaskById_taskId);
        System.out.println("retrieveTaskById.result=" + _retrieveTaskById__return);


        }
        {
        System.out.println("Invoking checkValidAppStatus...");
        java.lang.String _checkValidAppStatus_appName = "_checkValidAppStatus_appName-338311324";
        java.lang.String _checkValidAppStatus_appVersion = "_checkValidAppStatus_appVersion986889824";
        java.lang.String _checkValidAppStatus__return = port.checkValidAppStatus(_checkValidAppStatus_appName, _checkValidAppStatus_appVersion);
        System.out.println("checkValidAppStatus.result=" + _checkValidAppStatus__return);


        }
        {
        System.out.println("Invoking submitToLoanProspectorSeamless...");
        java.lang.String _submitToLoanProspectorSeamless_sTicket = "_submitToLoanProspectorSeamless_sTicket-160146560";
        java.lang.String _submitToLoanProspectorSeamless_sLNm = "_submitToLoanProspectorSeamless_sLNm-1290292254";
        java.lang.String _submitToLoanProspectorSeamless_lpUserId = "_submitToLoanProspectorSeamless_lpUserId-692380327";
        java.lang.String _submitToLoanProspectorSeamless_lpPassword = "_submitToLoanProspectorSeamless_lpPassword1117437559";
        java.lang.String _submitToLoanProspectorSeamless_creditMethod = "_submitToLoanProspectorSeamless_creditMethod381008969";
        java.lang.String _submitToLoanProspectorSeamless_craProvider = "_submitToLoanProspectorSeamless_craProvider986206577";
        java.lang.String _submitToLoanProspectorSeamless_borrowerCreditInfoXml = "_submitToLoanProspectorSeamless_borrowerCreditInfoXml1077100545";
        java.lang.String _submitToLoanProspectorSeamless__return = port.submitToLoanProspectorSeamless(_submitToLoanProspectorSeamless_sTicket, _submitToLoanProspectorSeamless_sLNm, _submitToLoanProspectorSeamless_lpUserId, _submitToLoanProspectorSeamless_lpPassword, _submitToLoanProspectorSeamless_creditMethod, _submitToLoanProspectorSeamless_craProvider, _submitToLoanProspectorSeamless_borrowerCreditInfoXml);
        System.out.println("submitToLoanProspectorSeamless.result=" + _submitToLoanProspectorSeamless__return);


        }
        {
        System.out.println("Invoking listMyActiveTaskList...");
        java.lang.String _listMyActiveTaskList_sTicket = "_listMyActiveTaskList_sTicket669631197";
        java.lang.String _listMyActiveTaskList__return = port.listMyActiveTaskList(_listMyActiveTaskList_sTicket);
        System.out.println("listMyActiveTaskList.result=" + _listMyActiveTaskList__return);


        }
        {
        System.out.println("Invoking retrieveLoanActivityList...");
        java.lang.String _retrieveLoanActivityList_sTicket = "_retrieveLoanActivityList_sTicket298646615";
        java.lang.String _retrieveLoanActivityList_sLNm = "_retrieveLoanActivityList_sLNm-1939970943";
        int _retrieveLoanActivityList_version = -1512939622;
        java.lang.String _retrieveLoanActivityList__return = port.retrieveLoanActivityList(_retrieveLoanActivityList_sTicket, _retrieveLoanActivityList_sLNm, _retrieveLoanActivityList_version);
        System.out.println("retrieveLoanActivityList.result=" + _retrieveLoanActivityList__return);


        }
        {
        System.out.println("Invoking uploadLONXml...");
        java.lang.String _uploadLONXml_sTicket = "_uploadLONXml_sTicket-157525805";
        java.lang.String _uploadLONXml_loanId = "_uploadLONXml_loanId-646191429";
        java.lang.String _uploadLONXml_sXmlData = "_uploadLONXml_sXmlData-136978001";
        java.lang.String _uploadLONXml__return = port.uploadLONXml(_uploadLONXml_sTicket, _uploadLONXml_loanId, _uploadLONXml_sXmlData);
        System.out.println("uploadLONXml.result=" + _uploadLONXml__return);


        }
        {
        System.out.println("Invoking clearModifiedLoansList...");
        java.lang.String _clearModifiedLoansList_sTicket = "_clearModifiedLoansList_sTicket-861476909";
        javax.xml.datatype.XMLGregorianCalendar _clearModifiedLoansList_lastModifiedDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-02-12T20:37:58.628+05:30");
        port.clearModifiedLoansList(_clearModifiedLoansList_sTicket, _clearModifiedLoansList_lastModifiedDate);


        }
        {
        System.out.println("Invoking lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck...");
        java.lang.String _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket = "_lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket-1053457763";
        java.lang.String _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm = "_lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm-1863259437";
        java.lang.String _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId = "_lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId-426055974";
        java.math.BigDecimal _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedRate = new java.math.BigDecimal("6084857158060317577.3969419487277651778");
        java.math.BigDecimal _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedFee = new java.math.BigDecimal("8081877415472461872.2060699595232536864");
        java.lang.String _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId = "_lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId928333384";
        boolean _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_skipDuplicateCheck = false;
        java.lang.String _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck__return = port.lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck(_lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sTicket, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_sLNm, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_lLpTemplateId, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedRate, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_requestedFee, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_rateOptionId, _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck_skipDuplicateCheck);
        System.out.println("lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck.result=" + _lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck__return);


        }
        {
        System.out.println("Invoking retrieveCustomReport...");
        java.lang.String _retrieveCustomReport_sTicket = "_retrieveCustomReport_sTicket1158320698";
        java.lang.String _retrieveCustomReport_sQueryNm = "_retrieveCustomReport_sQueryNm-1445193295";
        boolean _retrieveCustomReport_includeAllWithAccess = false;
        java.lang.String _retrieveCustomReport__return = port.retrieveCustomReport(_retrieveCustomReport_sTicket, _retrieveCustomReport_sQueryNm, _retrieveCustomReport_includeAllWithAccess);
        System.out.println("retrieveCustomReport.result=" + _retrieveCustomReport__return);


        }
        {
        System.out.println("Invoking submitToDesktopOriginator...");
        java.lang.String _submitToDesktopOriginator_sTicket = "_submitToDesktopOriginator_sTicket1972696297";
        java.lang.String _submitToDesktopOriginator_sLNm = "_submitToDesktopOriginator_sLNm1681805548";
        java.lang.String _submitToDesktopOriginator_doUserName = "_submitToDesktopOriginator_doUserName-808481042";
        java.lang.String _submitToDesktopOriginator_doPassword = "_submitToDesktopOriginator_doPassword-1357399380";
        java.lang.String _submitToDesktopOriginator__return = port.submitToDesktopOriginator(_submitToDesktopOriginator_sTicket, _submitToDesktopOriginator_sLNm, _submitToDesktopOriginator_doUserName, _submitToDesktopOriginator_doPassword);
        System.out.println("submitToDesktopOriginator.result=" + _submitToDesktopOriginator__return);


        }
        {
        System.out.println("Invoking retrieveUsersAssignedToLoan...");
        java.lang.String _retrieveUsersAssignedToLoan_sTicket = "_retrieveUsersAssignedToLoan_sTicket-1275454834";
        java.lang.String _retrieveUsersAssignedToLoan_sLNm = "_retrieveUsersAssignedToLoan_sLNm-1997760464";
        java.lang.String _retrieveUsersAssignedToLoan__return = port.retrieveUsersAssignedToLoan(_retrieveUsersAssignedToLoan_sTicket, _retrieveUsersAssignedToLoan_sLNm);
        System.out.println("retrieveUsersAssignedToLoan.result=" + _retrieveUsersAssignedToLoan__return);


        }
        {
        System.out.println("Invoking search...");
        java.lang.String _search_sTicket = "_search_sTicket-1566382011";
        java.lang.String _search_sSearchFilterXml = "_search_sSearchFilterXml-1626671082";
        java.lang.String _search__return = port.search(_search_sTicket, _search_sSearchFilterXml);
        System.out.println("search.result=" + _search__return);


        }
        {
        System.out.println("Invoking submitToDesktopUnderwriter...");
        java.lang.String _submitToDesktopUnderwriter_sTicket = "_submitToDesktopUnderwriter_sTicket684897630";
        java.lang.String _submitToDesktopUnderwriter_sLNm = "_submitToDesktopUnderwriter_sLNm-2109527353";
        java.lang.String _submitToDesktopUnderwriter_duUserName = "_submitToDesktopUnderwriter_duUserName1500155965";
        java.lang.String _submitToDesktopUnderwriter_duPassword = "_submitToDesktopUnderwriter_duPassword-1612185121";
        java.lang.String _submitToDesktopUnderwriter__return = port.submitToDesktopUnderwriter(_submitToDesktopUnderwriter_sTicket, _submitToDesktopUnderwriter_sLNm, _submitToDesktopUnderwriter_duUserName, _submitToDesktopUnderwriter_duPassword);
        System.out.println("submitToDesktopUnderwriter.result=" + _submitToDesktopUnderwriter__return);


        }
        {
        System.out.println("Invoking listModifiedLoansByAppCode...");
        java.lang.String _listModifiedLoansByAppCode_sTicket = "_listModifiedLoansByAppCode_sTicket-835899093";
        java.lang.String _listModifiedLoansByAppCode_appCode = "_listModifiedLoansByAppCode_appCode1171178473";
        java.lang.String _listModifiedLoansByAppCode__return = port.listModifiedLoansByAppCode(_listModifiedLoansByAppCode_sTicket, _listModifiedLoansByAppCode_appCode);
        System.out.println("listModifiedLoansByAppCode.result=" + _listModifiedLoansByAppCode__return);


        }
        {
        System.out.println("Invoking clearModifiedLoanByName...");
        java.lang.String _clearModifiedLoanByName_sTicket = "_clearModifiedLoanByName_sTicket134773078";
        java.lang.String _clearModifiedLoanByName_loanName = "_clearModifiedLoanByName_loanName-1977915153";
        port.clearModifiedLoanByName(_clearModifiedLoanByName_sTicket, _clearModifiedLoanByName_loanName);


        }

        System.exit(0);
    }

}
