
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.lendersoffice.los.webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-02-12T20:37:58.779+05:30
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "Loan",
                      portName = "LoanSoap12",
                      targetNamespace = "http://www.lendersoffice.com/los/webservices/",
                      wsdlLocation = "https://webservices.lendingqb.com/los/webservice/Loan.asmx?WSDL",
                      endpointInterface = "com.lendersoffice.los.webservices.LoanSoap")
                      
public class LoanSoapImpl1 implements LoanSoap {

    private static final Logger LOG = Logger.getLogger(LoanSoapImpl1.class.getName());

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#save(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  sDataContent ,)int  format )*
     */
    public java.lang.String save(java.lang.String sTicket,java.lang.String sLNm,java.lang.String sDataContent,int format) { 
        LOG.info("Executing operation save");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(sDataContent);
        System.out.println(format);
        try {
            java.lang.String _return = "_return702961277";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#loadMismo23ByLoanName(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  sXmlQuery )*
     */
    public java.lang.String loadMismo23ByLoanName(java.lang.String sTicket,java.lang.String sLNm,java.lang.String sXmlQuery) { 
        LOG.info("Executing operation loadMismo23ByLoanName");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(sXmlQuery);
        try {
            java.lang.String _return = "_return1221212268";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#deleteLoan(java.lang.String  sTicket ,)java.lang.String  sLNm )*
     */
    public java.lang.String deleteLoan(java.lang.String sTicket,java.lang.String sLNm) { 
        LOG.info("Executing operation deleteLoan");
        System.out.println(sTicket);
        System.out.println(sLNm);
        try {
            java.lang.String _return = "_return-983539310";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#breakBrokerRateLock(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  reason )*
     */
    public java.lang.String breakBrokerRateLock(java.lang.String sTicket,java.lang.String sLNm,java.lang.String reason) { 
        LOG.info("Executing operation breakBrokerRateLock");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(reason);
        try {
            java.lang.String _return = "_return1970159559";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#submitTotalScorecard(java.lang.String  sTicket ,)java.lang.String  sLNm )*
     */
    public java.lang.String submitTotalScorecard(java.lang.String sTicket,java.lang.String sLNm) { 
        LOG.info("Executing operation submitTotalScorecard");
        System.out.println(sTicket);
        System.out.println(sLNm);
        try {
            java.lang.String _return = "_return32113602";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#lockLoanProgramWithRateOptionId(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  lLpTemplateId ,)java.math.BigDecimal  requestedRate ,)java.math.BigDecimal  requestedFee ,)java.lang.String  rateOptionId )*
     */
    public java.lang.String lockLoanProgramWithRateOptionId(java.lang.String sTicket,java.lang.String sLNm,java.lang.String lLpTemplateId,java.math.BigDecimal requestedRate,java.math.BigDecimal requestedFee,java.lang.String rateOptionId) { 
        LOG.info("Executing operation lockLoanProgramWithRateOptionId");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(lLpTemplateId);
        System.out.println(requestedRate);
        System.out.println(requestedFee);
        System.out.println(rateOptionId);
        try {
            java.lang.String _return = "_return1341953177";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#runInternalPricing(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  sXmlData )*
     */
    public java.lang.String runInternalPricing(java.lang.String sTicket,java.lang.String sLNm,java.lang.String sXmlData) { 
        LOG.info("Executing operation runInternalPricing");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(sXmlData);
        try {
            java.lang.String _return = "_return-378857632";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#lockLoanProgramAndSkipDuplicateCheck(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  lLpTemplateId ,)java.math.BigDecimal  requestedRate ,)java.math.BigDecimal  requestedFee ,)boolean  skipDuplicateCheck )*
     */
    public java.lang.String lockLoanProgramAndSkipDuplicateCheck(java.lang.String sTicket,java.lang.String sLNm,java.lang.String lLpTemplateId,java.math.BigDecimal requestedRate,java.math.BigDecimal requestedFee,boolean skipDuplicateCheck) { 
        LOG.info("Executing operation lockLoanProgramAndSkipDuplicateCheck");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(lLpTemplateId);
        System.out.println(requestedRate);
        System.out.println(requestedFee);
        System.out.println(skipDuplicateCheck);
        try {
            java.lang.String _return = "_return-277008924";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#parseFnma32ToLoXml(java.lang.String  sTicket ,)java.lang.String  fnma32Content ,)java.lang.String  sXmlQuery )*
     */
    public java.lang.String parseFnma32ToLoXml(java.lang.String sTicket,java.lang.String fnma32Content,java.lang.String sXmlQuery) { 
        LOG.info("Executing operation parseFnma32ToLoXml");
        System.out.println(sTicket);
        System.out.println(fnma32Content);
        System.out.println(sXmlQuery);
        try {
            java.lang.String _return = "_return1785994785";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#submitToDesktopUnderwriterSeamless(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  duUserName ,)java.lang.String  duPassword ,)java.lang.String  institutionId ,)java.lang.String  craProvider ,)java.lang.String  craLoginName ,)java.lang.String  craPassword ,)boolean  isCopyLiabilities )*
     */
    public java.lang.String submitToDesktopUnderwriterSeamless(java.lang.String sTicket,java.lang.String sLNm,java.lang.String duUserName,java.lang.String duPassword,java.lang.String institutionId,java.lang.String craProvider,java.lang.String craLoginName,java.lang.String craPassword,boolean isCopyLiabilities) { 
        LOG.info("Executing operation submitToDesktopUnderwriterSeamless");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(duUserName);
        System.out.println(duPassword);
        System.out.println(institutionId);
        System.out.println(craProvider);
        System.out.println(craLoginName);
        System.out.println(craPassword);
        System.out.println(isCopyLiabilities);
        try {
            java.lang.String _return = "_return494232111";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#submitToDesktopUnderwriterWithInstituteId(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  duUserName ,)java.lang.String  duPassword ,)java.lang.String  institutionId )*
     */
    public java.lang.String submitToDesktopUnderwriterWithInstituteId(java.lang.String sTicket,java.lang.String sLNm,java.lang.String duUserName,java.lang.String duPassword,java.lang.String institutionId) { 
        LOG.info("Executing operation submitToDesktopUnderwriterWithInstituteId");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(duUserName);
        System.out.println(duPassword);
        System.out.println(institutionId);
        try {
            java.lang.String _return = "_return-1275883383";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#uploadPDFDocument(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  documentType ,)java.lang.String  notes ,)java.lang.String  sDataContent )*
     */
    public java.lang.String uploadPDFDocument(java.lang.String sTicket,java.lang.String sLNm,java.lang.String documentType,java.lang.String notes,java.lang.String sDataContent) { 
        LOG.info("Executing operation uploadPDFDocument");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(documentType);
        System.out.println(notes);
        System.out.println(sDataContent);
        try {
            java.lang.String _return = "_return-488415922";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#clearModifiedLoanByNameByAppCode(java.lang.String  sTicket ,)java.lang.String  loanName ,)java.lang.String  appCode )*
     */
    public void clearModifiedLoanByNameByAppCode(java.lang.String sTicket,java.lang.String loanName,java.lang.String appCode) { 
        LOG.info("Executing operation clearModifiedLoanByNameByAppCode");
        System.out.println(sTicket);
        System.out.println(loanName);
        System.out.println(appCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#submitToFannieMaeEarlyCheck(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  duUserName ,)java.lang.String  duPassword ,)java.lang.String  institutionId )*
     */
    public java.lang.String submitToFannieMaeEarlyCheck(java.lang.String sTicket,java.lang.String sLNm,java.lang.String duUserName,java.lang.String duPassword,java.lang.String institutionId) { 
        LOG.info("Executing operation submitToFannieMaeEarlyCheck");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(duUserName);
        System.out.println(duPassword);
        System.out.println(institutionId);
        try {
            java.lang.String _return = "_return-1229346174";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#getPdfByLoanName(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  sPdfName )*
     */
    public java.lang.String getPdfByLoanName(java.lang.String sTicket,java.lang.String sLNm,java.lang.String sPdfName) { 
        LOG.info("Executing operation getPdfByLoanName");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(sPdfName);
        try {
            java.lang.String _return = "_return504844373";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  lLpTemplateId ,)java.math.BigDecimal  requestedRate ,)java.math.BigDecimal  requestedFee ,)java.lang.String  rateOptionId ,)boolean  skipDuplicateCheck )*
     */
    public java.lang.String registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck(java.lang.String sTicket,java.lang.String sLNm,java.lang.String lLpTemplateId,java.math.BigDecimal requestedRate,java.math.BigDecimal requestedFee,java.lang.String rateOptionId,boolean skipDuplicateCheck) { 
        LOG.info("Executing operation registerLoanProgramWithRateOptionIdAndSkipDuplicateCheck");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(lLpTemplateId);
        System.out.println(requestedRate);
        System.out.println(requestedFee);
        System.out.println(rateOptionId);
        System.out.println(skipDuplicateCheck);
        try {
            java.lang.String _return = "_return-831434391";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#registerLoanProgramWithRateOptionId(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  lLpTemplateId ,)java.math.BigDecimal  requestedRate ,)java.math.BigDecimal  requestedFee ,)java.lang.String  rateOptionId )*
     */
    public java.lang.String registerLoanProgramWithRateOptionId(java.lang.String sTicket,java.lang.String sLNm,java.lang.String lLpTemplateId,java.math.BigDecimal requestedRate,java.math.BigDecimal requestedFee,java.lang.String rateOptionId) { 
        LOG.info("Executing operation registerLoanProgramWithRateOptionId");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(lLpTemplateId);
        System.out.println(requestedRate);
        System.out.println(requestedFee);
        System.out.println(rateOptionId);
        try {
            java.lang.String _return = "_return136549980";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#lockLoanProgram(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  lLpTemplateId ,)java.math.BigDecimal  requestedRate ,)java.math.BigDecimal  requestedFee )*
     */
    public java.lang.String lockLoanProgram(java.lang.String sTicket,java.lang.String sLNm,java.lang.String lLpTemplateId,java.math.BigDecimal requestedRate,java.math.BigDecimal requestedFee) { 
        LOG.info("Executing operation lockLoanProgram");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(lLpTemplateId);
        System.out.println(requestedRate);
        System.out.println(requestedFee);
        try {
            java.lang.String _return = "_return-58786529";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#importFromFannieMae(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  doUserName ,)java.lang.String  doPassword ,)boolean  isImportCredit )*
     */
    public java.lang.String importFromFannieMae(java.lang.String sTicket,java.lang.String sLNm,java.lang.String doUserName,java.lang.String doPassword,boolean isImportCredit) { 
        LOG.info("Executing operation importFromFannieMae");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(doUserName);
        System.out.println(doPassword);
        System.out.println(isImportCredit);
        try {
            java.lang.String _return = "_return-1490588421";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#retrieveRecentActiveLoanList(java.lang.String  sTicket )*
     */
    public java.lang.String retrieveRecentActiveLoanList(java.lang.String sTicket) { 
        LOG.info("Executing operation retrieveRecentActiveLoanList");
        System.out.println(sTicket);
        try {
            java.lang.String _return = "_return-113984302";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#retrievePmlLoanList(java.lang.String  sTicket )*
     */
    public java.lang.String retrievePmlLoanList(java.lang.String sTicket) { 
        LOG.info("Executing operation retrievePmlLoanList");
        System.out.println(sTicket);
        try {
            java.lang.String _return = "_return1768258986";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#clearModifiedLoansListByAppCode(java.lang.String  sTicket ,)javax.xml.datatype.XMLGregorianCalendar  lastModifiedDate ,)java.lang.String  appCode )*
     */
    public void clearModifiedLoansListByAppCode(java.lang.String sTicket,javax.xml.datatype.XMLGregorianCalendar lastModifiedDate,java.lang.String appCode) { 
        LOG.info("Executing operation clearModifiedLoansListByAppCode");
        System.out.println(sTicket);
        System.out.println(lastModifiedDate);
        System.out.println(appCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#removeRequestedRate(java.lang.String  sTicket ,)java.lang.String  sLNm )*
     */
    public java.lang.String removeRequestedRate(java.lang.String sTicket,java.lang.String sLNm) { 
        LOG.info("Executing operation removeRequestedRate");
        System.out.println(sTicket);
        System.out.println(sLNm);
        try {
            java.lang.String _return = "_return1860456863";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#recievePdf(java.lang.String  authTicket ,)java.lang.String  sLNm ,)java.lang.String  documentClassification ,)java.lang.String  base64PdfContent )*
     */
    public java.lang.String recievePdf(java.lang.String authTicket,java.lang.String sLNm,java.lang.String documentClassification,java.lang.String base64PdfContent) { 
        LOG.info("Executing operation recievePdf");
        System.out.println(authTicket);
        System.out.println(sLNm);
        System.out.println(documentClassification);
        System.out.println(base64PdfContent);
        try {
            java.lang.String _return = "_return-92545693";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#getDesktopUnderwriterCasefileStatus(java.lang.String  sTicket ,)java.lang.String  sDuCaseId ,)java.lang.String  duUserName ,)java.lang.String  duPassword ,)boolean  isDo )*
     */
    public java.lang.String getDesktopUnderwriterCasefileStatus(java.lang.String sTicket,java.lang.String sDuCaseId,java.lang.String duUserName,java.lang.String duPassword,boolean isDo) { 
        LOG.info("Executing operation getDesktopUnderwriterCasefileStatus");
        System.out.println(sTicket);
        System.out.println(sDuCaseId);
        System.out.println(duUserName);
        System.out.println(duPassword);
        System.out.println(isDo);
        try {
            java.lang.String _return = "_return1589787714";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#createWithULDD(java.lang.String  sTicket ,)java.lang.String  xml )*
     */
    public java.lang.String createWithULDD(java.lang.String sTicket,java.lang.String xml) { 
        LOG.info("Executing operation createWithULDD");
        System.out.println(sTicket);
        System.out.println(xml);
        try {
            java.lang.String _return = "_return-296457665";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#prepareLoanForResubmission(java.lang.String  sTicket ,)java.lang.String  sLNm )*
     */
    public java.lang.String prepareLoanForResubmission(java.lang.String sTicket,java.lang.String sLNm) { 
        LOG.info("Executing operation prepareLoanForResubmission");
        System.out.println(sTicket);
        System.out.println(sLNm);
        try {
            java.lang.String _return = "_return-1042591644";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#listEdocsByLoanNumber(java.lang.String  sTicket ,)java.lang.String  sLNm )*
     */
    public java.lang.String listEdocsByLoanNumber(java.lang.String sTicket,java.lang.String sLNm) { 
        LOG.info("Executing operation listEdocsByLoanNumber");
        System.out.println(sTicket);
        System.out.println(sLNm);
        try {
            java.lang.String _return = "_return-155247901";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#retrieveClosingCostTemplateFeeList(java.lang.String  sTicket ,)java.lang.String  closingCostName )*
     */
    public java.lang.String retrieveClosingCostTemplateFeeList(java.lang.String sTicket,java.lang.String closingCostName) { 
        LOG.info("Executing operation retrieveClosingCostTemplateFeeList");
        System.out.println(sTicket);
        System.out.println(closingCostName);
        try {
            java.lang.String _return = "_return96155475";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#createWithFannieMaeFile(java.lang.String  sTicket ,)java.lang.String  content )*
     */
    public java.lang.String createWithFannieMaeFile(java.lang.String sTicket,java.lang.String content) { 
        LOG.info("Executing operation createWithFannieMaeFile");
        System.out.println(sTicket);
        System.out.println(content);
        try {
            java.lang.String _return = "_return-510461454";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#isLoanExisted(java.lang.String  sTicket ,)java.lang.String  sLNm )*
     */
    public boolean isLoanExisted(java.lang.String sTicket,java.lang.String sLNm) { 
        LOG.info("Executing operation isLoanExisted");
        System.out.println(sTicket);
        System.out.println(sLNm);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#getDesktopUnderwriterCasefileStatusByLoanFile(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  duUserName ,)java.lang.String  duPassword ,)boolean  isDo )*
     */
    public java.lang.String getDesktopUnderwriterCasefileStatusByLoanFile(java.lang.String sTicket,java.lang.String sLNm,java.lang.String duUserName,java.lang.String duPassword,boolean isDo) { 
        LOG.info("Executing operation getDesktopUnderwriterCasefileStatusByLoanFile");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(duUserName);
        System.out.println(duPassword);
        System.out.println(isDo);
        try {
            java.lang.String _return = "_return1294186472";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#saveMismo23(java.lang.String  sTicket ,)java.lang.String  loanId ,)java.lang.String  sXmlData )*
     */
    public java.lang.String saveMismo23(java.lang.String sTicket,java.lang.String loanId,java.lang.String sXmlData) { 
        LOG.info("Executing operation saveMismo23");
        System.out.println(sTicket);
        System.out.println(loanId);
        System.out.println(sXmlData);
        try {
            java.lang.String _return = "_return1226477175";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#deleteApplicant(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  applicantSSN )*
     */
    public java.lang.String deleteApplicant(java.lang.String sTicket,java.lang.String sLNm,java.lang.String applicantSSN) { 
        LOG.info("Executing operation deleteApplicant");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(applicantSSN);
        try {
            java.lang.String _return = "_return-1364654071";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#importFromFannieMaeWithInstitutionId(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  doUserName ,)java.lang.String  doPassword ,)java.lang.String  lenderInstitutionIdentifer ,)boolean  isImportCredit )*
     */
    public java.lang.String importFromFannieMaeWithInstitutionId(java.lang.String sTicket,java.lang.String sLNm,java.lang.String doUserName,java.lang.String doPassword,java.lang.String lenderInstitutionIdentifer,boolean isImportCredit) { 
        LOG.info("Executing operation importFromFannieMaeWithInstitutionId");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(doUserName);
        System.out.println(doPassword);
        System.out.println(lenderInstitutionIdentifer);
        System.out.println(isImportCredit);
        try {
            java.lang.String _return = "_return-2096264530";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#listModifiedEDocsByAppCode(java.lang.String  sTicket ,)java.lang.String  appCode ,)java.lang.String  modifiedDate )*
     */
    public java.lang.String listModifiedEDocsByAppCode(java.lang.String sTicket,java.lang.String appCode,java.lang.String modifiedDate) { 
        LOG.info("Executing operation listModifiedEDocsByAppCode");
        System.out.println(sTicket);
        System.out.println(appCode);
        System.out.println(modifiedDate);
        try {
            java.lang.String _return = "_return-2128547522";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#create(java.lang.String  sTicket ,)java.lang.String  sTemplateNm )*
     */
    public java.lang.String create(java.lang.String sTicket,java.lang.String sTemplateNm) { 
        LOG.info("Executing operation create");
        System.out.println(sTicket);
        System.out.println(sTemplateNm);
        try {
            java.lang.String _return = "_return145853667";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#createWithCalyxPointFile(java.lang.String  sTicket ,)java.lang.String  base64Content )*
     */
    public java.lang.String createWithCalyxPointFile(java.lang.String sTicket,java.lang.String base64Content) { 
        LOG.info("Executing operation createWithCalyxPointFile");
        System.out.println(sTicket);
        System.out.println(base64Content);
        try {
            java.lang.String _return = "_return1837623842";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#registerLoanProgramAndSkipDuplicateCheck(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  lLpTemplateId ,)java.math.BigDecimal  requestedRate ,)java.math.BigDecimal  requestedFee ,)boolean  skipDuplicateCheck )*
     */
    public java.lang.String registerLoanProgramAndSkipDuplicateCheck(java.lang.String sTicket,java.lang.String sLNm,java.lang.String lLpTemplateId,java.math.BigDecimal requestedRate,java.math.BigDecimal requestedFee,boolean skipDuplicateCheck) { 
        LOG.info("Executing operation registerLoanProgramAndSkipDuplicateCheck");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(lLpTemplateId);
        System.out.println(requestedRate);
        System.out.println(requestedFee);
        System.out.println(skipDuplicateCheck);
        try {
            java.lang.String _return = "_return-1789251553";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#runQuickPricer(java.lang.String  sTicket ,)java.lang.String  sXmlData )*
     */
    public java.lang.String runQuickPricer(java.lang.String sTicket,java.lang.String sXmlData) { 
        LOG.info("Executing operation runQuickPricer");
        System.out.println(sTicket);
        System.out.println(sXmlData);
        try {
            java.lang.String _return = "_return1905299341";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#downloadEdocsByShippingTemplate(java.lang.String  sTicket ,)java.lang.String  sShippingTemplateName ,)java.lang.String  sLNm ,)boolean  includeScreenedDocs ,)boolean  includeDocsWithoutStatus )*
     */
    public byte[] downloadEdocsByShippingTemplate(java.lang.String sTicket,java.lang.String sShippingTemplateName,java.lang.String sLNm,boolean includeScreenedDocs,boolean includeDocsWithoutStatus) { 
        LOG.info("Executing operation downloadEdocsByShippingTemplate");
        System.out.println(sTicket);
        System.out.println(sShippingTemplateName);
        System.out.println(sLNm);
        System.out.println(includeScreenedDocs);
        System.out.println(includeDocsWithoutStatus);
        try {
            byte[] _return = new byte[] {};
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#taskResolve(java.lang.String  sTicket ,)java.lang.String  taskId ,)java.lang.String  subject ,)java.lang.String  comment ,)java.lang.String  dueDate ,)java.lang.String  assignedTo )*
     */
    public java.lang.String taskResolve(java.lang.String sTicket,java.lang.String taskId,java.lang.String subject,java.lang.String comment,java.lang.String dueDate,java.lang.String assignedTo) { 
        LOG.info("Executing operation taskResolve");
        System.out.println(sTicket);
        System.out.println(taskId);
        System.out.println(subject);
        System.out.println(comment);
        System.out.println(dueDate);
        System.out.println(assignedTo);
        try {
            java.lang.String _return = "_return1093502411";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#taskEdit(java.lang.String  sTicket ,)java.lang.String  taskId ,)java.lang.String  subject ,)java.lang.String  comment ,)java.lang.String  dueDate ,)java.lang.String  assignedTo )*
     */
    public java.lang.String taskEdit(java.lang.String sTicket,java.lang.String taskId,java.lang.String subject,java.lang.String comment,java.lang.String dueDate,java.lang.String assignedTo) { 
        LOG.info("Executing operation taskEdit");
        System.out.println(sTicket);
        System.out.println(taskId);
        System.out.println(subject);
        System.out.println(comment);
        System.out.println(dueDate);
        System.out.println(assignedTo);
        try {
            java.lang.String _return = "_return-1407510698";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#createLead(java.lang.String  sTicket ,)java.lang.String  sTemplateNm )*
     */
    public java.lang.String createLead(java.lang.String sTicket,java.lang.String sTemplateNm) { 
        LOG.info("Executing operation createLead");
        System.out.println(sTicket);
        System.out.println(sTemplateNm);
        try {
            java.lang.String _return = "_return-159409390";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#downloadEdocsPdfById(java.lang.String  sTicket ,)java.lang.String  docId )*
     */
    public byte[] downloadEdocsPdfById(java.lang.String sTicket,java.lang.String docId) { 
        LOG.info("Executing operation downloadEdocsPdfById");
        System.out.println(sTicket);
        System.out.println(docId);
        try {
            byte[] _return = new byte[] {};
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#load(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  sXmlQuery ,)int  format )*
     */
    public java.lang.String load(java.lang.String sTicket,java.lang.String sLNm,java.lang.String sXmlQuery,int format) { 
        LOG.info("Executing operation load");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(sXmlQuery);
        System.out.println(format);
        try {
            java.lang.String _return = "_return-1458905818";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#listModifiedLoans(java.lang.String  sTicket )*
     */
    public java.lang.String listModifiedLoans(java.lang.String sTicket) { 
        LOG.info("Executing operation listModifiedLoans");
        System.out.println(sTicket);
        try {
            java.lang.String _return = "_return1790808272";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#createWithDesktopUnderwriter(java.lang.String  sTicket ,)java.lang.String  doUserName ,)java.lang.String  doPassword ,)java.lang.String  sDuCaseId ,)boolean  isImportCredit )*
     */
    public java.lang.String createWithDesktopUnderwriter(java.lang.String sTicket,java.lang.String doUserName,java.lang.String doPassword,java.lang.String sDuCaseId,boolean isImportCredit) { 
        LOG.info("Executing operation createWithDesktopUnderwriter");
        System.out.println(sTicket);
        System.out.println(doUserName);
        System.out.println(doPassword);
        System.out.println(sDuCaseId);
        System.out.println(isImportCredit);
        try {
            java.lang.String _return = "_return-182870630";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#listClosingCostTemplateName(java.lang.String  sTicket )*
     */
    public java.lang.String listClosingCostTemplateName(java.lang.String sTicket) { 
        LOG.info("Executing operation listClosingCostTemplateName");
        System.out.println(sTicket);
        try {
            java.lang.String _return = "_return-1428796600";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#runQuickPricerForLockDesk(java.lang.String  sTicket ,)java.lang.String  sXmlData )*
     */
    public java.lang.String runQuickPricerForLockDesk(java.lang.String sTicket,java.lang.String sXmlData) { 
        LOG.info("Executing operation runQuickPricerForLockDesk");
        System.out.println(sTicket);
        System.out.println(sXmlData);
        try {
            java.lang.String _return = "_return770028543";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#registerLoanProgram(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  lLpTemplateId ,)java.math.BigDecimal  requestedRate ,)java.math.BigDecimal  requestedFee )*
     */
    public java.lang.String registerLoanProgram(java.lang.String sTicket,java.lang.String sLNm,java.lang.String lLpTemplateId,java.math.BigDecimal requestedRate,java.math.BigDecimal requestedFee) { 
        LOG.info("Executing operation registerLoanProgram");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(lLpTemplateId);
        System.out.println(requestedRate);
        System.out.println(requestedFee);
        try {
            java.lang.String _return = "_return-1829561930";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#uploadPDFDocumentToApp(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  aAppId ,)java.lang.String  documentType ,)java.lang.String  notes ,)java.lang.String  sDataContent )*
     */
    public java.lang.String uploadPDFDocumentToApp(java.lang.String sTicket,java.lang.String sLNm,java.lang.String aAppId,java.lang.String documentType,java.lang.String notes,java.lang.String sDataContent) { 
        LOG.info("Executing operation uploadPDFDocumentToApp");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(aAppId);
        System.out.println(documentType);
        System.out.println(notes);
        System.out.println(sDataContent);
        try {
            java.lang.String _return = "_return665782633";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#retrieveTaskById(java.lang.String  sTicket ,)java.lang.String  taskId )*
     */
    public java.lang.String retrieveTaskById(java.lang.String sTicket,java.lang.String taskId) { 
        LOG.info("Executing operation retrieveTaskById");
        System.out.println(sTicket);
        System.out.println(taskId);
        try {
            java.lang.String _return = "_return697082742";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#checkValidAppStatus(java.lang.String  appName ,)java.lang.String  appVersion )*
     */
    public java.lang.String checkValidAppStatus(java.lang.String appName,java.lang.String appVersion) { 
        LOG.info("Executing operation checkValidAppStatus");
        System.out.println(appName);
        System.out.println(appVersion);
        try {
            java.lang.String _return = "_return1023928316";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#submitToLoanProspectorSeamless(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  lpUserId ,)java.lang.String  lpPassword ,)java.lang.String  creditMethod ,)java.lang.String  craProvider ,)java.lang.String  borrowerCreditInfoXml )*
     */
    public java.lang.String submitToLoanProspectorSeamless(java.lang.String sTicket,java.lang.String sLNm,java.lang.String lpUserId,java.lang.String lpPassword,java.lang.String creditMethod,java.lang.String craProvider,java.lang.String borrowerCreditInfoXml) { 
        LOG.info("Executing operation submitToLoanProspectorSeamless");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(lpUserId);
        System.out.println(lpPassword);
        System.out.println(creditMethod);
        System.out.println(craProvider);
        System.out.println(borrowerCreditInfoXml);
        try {
            java.lang.String _return = "_return-923846822";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#listMyActiveTaskList(java.lang.String  sTicket )*
     */
    public java.lang.String listMyActiveTaskList(java.lang.String sTicket) { 
        LOG.info("Executing operation listMyActiveTaskList");
        System.out.println(sTicket);
        try {
            java.lang.String _return = "_return64529311";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#retrieveLoanActivityList(java.lang.String  sTicket ,)java.lang.String  sLNm ,)int  version )*
     */
    public java.lang.String retrieveLoanActivityList(java.lang.String sTicket,java.lang.String sLNm,int version) { 
        LOG.info("Executing operation retrieveLoanActivityList");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(version);
        try {
            java.lang.String _return = "_return-1406854307";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#uploadLONXml(java.lang.String  sTicket ,)java.lang.String  loanId ,)java.lang.String  sXmlData )*
     */
    public java.lang.String uploadLONXml(java.lang.String sTicket,java.lang.String loanId,java.lang.String sXmlData) { 
        LOG.info("Executing operation uploadLONXml");
        System.out.println(sTicket);
        System.out.println(loanId);
        System.out.println(sXmlData);
        try {
            java.lang.String _return = "_return101880176";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#clearModifiedLoansList(java.lang.String  sTicket ,)javax.xml.datatype.XMLGregorianCalendar  lastModifiedDate )*
     */
    public void clearModifiedLoansList(java.lang.String sTicket,javax.xml.datatype.XMLGregorianCalendar lastModifiedDate) { 
        LOG.info("Executing operation clearModifiedLoansList");
        System.out.println(sTicket);
        System.out.println(lastModifiedDate);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  lLpTemplateId ,)java.math.BigDecimal  requestedRate ,)java.math.BigDecimal  requestedFee ,)java.lang.String  rateOptionId ,)boolean  skipDuplicateCheck )*
     */
    public java.lang.String lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck(java.lang.String sTicket,java.lang.String sLNm,java.lang.String lLpTemplateId,java.math.BigDecimal requestedRate,java.math.BigDecimal requestedFee,java.lang.String rateOptionId,boolean skipDuplicateCheck) { 
        LOG.info("Executing operation lockLoanProgramWithRateOptionIdAndSkipDuplicateCheck");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(lLpTemplateId);
        System.out.println(requestedRate);
        System.out.println(requestedFee);
        System.out.println(rateOptionId);
        System.out.println(skipDuplicateCheck);
        try {
            java.lang.String _return = "_return2107244002";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#retrieveCustomReport(java.lang.String  sTicket ,)java.lang.String  sQueryNm ,)boolean  includeAllWithAccess )*
     */
    public java.lang.String retrieveCustomReport(java.lang.String sTicket,java.lang.String sQueryNm,boolean includeAllWithAccess) { 
        LOG.info("Executing operation retrieveCustomReport");
        System.out.println(sTicket);
        System.out.println(sQueryNm);
        System.out.println(includeAllWithAccess);
        try {
            java.lang.String _return = "_return-1245828696";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#submitToDesktopOriginator(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  doUserName ,)java.lang.String  doPassword )*
     */
    public java.lang.String submitToDesktopOriginator(java.lang.String sTicket,java.lang.String sLNm,java.lang.String doUserName,java.lang.String doPassword) { 
        LOG.info("Executing operation submitToDesktopOriginator");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(doUserName);
        System.out.println(doPassword);
        try {
            java.lang.String _return = "_return836566807";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#retrieveUsersAssignedToLoan(java.lang.String  sTicket ,)java.lang.String  sLNm )*
     */
    public java.lang.String retrieveUsersAssignedToLoan(java.lang.String sTicket,java.lang.String sLNm) { 
        LOG.info("Executing operation retrieveUsersAssignedToLoan");
        System.out.println(sTicket);
        System.out.println(sLNm);
        try {
            java.lang.String _return = "_return-1485440030";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#search(java.lang.String  sTicket ,)java.lang.String  sSearchFilterXml )*
     */
    public java.lang.String search(java.lang.String sTicket,java.lang.String sSearchFilterXml) { 
        LOG.info("Executing operation search");
        System.out.println(sTicket);
        System.out.println(sSearchFilterXml);
        try {
            java.lang.String _return = "_return-1145028554";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#submitToDesktopUnderwriter(java.lang.String  sTicket ,)java.lang.String  sLNm ,)java.lang.String  duUserName ,)java.lang.String  duPassword )*
     */
    public java.lang.String submitToDesktopUnderwriter(java.lang.String sTicket,java.lang.String sLNm,java.lang.String duUserName,java.lang.String duPassword) { 
        LOG.info("Executing operation submitToDesktopUnderwriter");
        System.out.println(sTicket);
        System.out.println(sLNm);
        System.out.println(duUserName);
        System.out.println(duPassword);
        try {
            java.lang.String _return = "_return1696293849";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#listModifiedLoansByAppCode(java.lang.String  sTicket ,)java.lang.String  appCode )*
     */
    public java.lang.String listModifiedLoansByAppCode(java.lang.String sTicket,java.lang.String appCode) { 
        LOG.info("Executing operation listModifiedLoansByAppCode");
        System.out.println(sTicket);
        System.out.println(appCode);
        try {
            java.lang.String _return = "_return-923840588";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lendersoffice.los.webservices.LoanSoap#clearModifiedLoanByName(java.lang.String  sTicket ,)java.lang.String  loanName )*
     */
    public void clearModifiedLoanByName(java.lang.String sTicket,java.lang.String loanName) { 
        LOG.info("Executing operation clearModifiedLoanByName");
        System.out.println(sTicket);
        System.out.println(loanName);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
